"""``orchestrator init`` — scaffold a new project to use the orchestrator (G14).

The companion to ``doctor``: ``doctor`` *checks* environment readiness;
``init`` *writes the scaffold* for it. It generates a commented ``.env``
skeleton from the same ``ENV_GROUPS`` doctor checks (so the two never drift),
filling in only the keys that aren't already set — it never overwrites an
existing value, so re-running it is safe and only adds what's missing.

Pure functions (``render_env_template`` / ``missing_keys``) carry the logic so
they're unit-testable; the CLI command wires file I/O around them.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from orchestrator.doctor import ENV_GROUPS

# Known-useful optional vars worth scaffolding as commented hints, beyond the
# required groups doctor enforces.
_OPTIONAL_HINTS: tuple[tuple[str, str], ...] = (
    ("ORCHESTRATOR_DATABASE_URL", "Postgres URL (defaults to the docker-compose dev DB)"),
    ("SLACK_WEBHOOK_URL", "Slack incoming-webhook for approval-gate alerts (optional)"),
    ("SDLC_RUN_BUDGET_USD", "Per-run LLM spend cap; 0 disables enforcement (default 25)"),
    ("NOTION_API_TOKEN", "Notion integration token, if sourcing requirements from Notion"),
)


def render_env_template(existing: Mapping[str, str] | None = None) -> str:
    """Render a ``.env`` skeleton from ENV_GROUPS, omitting already-set keys.

    Every required var doctor checks gets a ``NAME=`` line under a commented
    group header; vars already present in ``existing`` are skipped (init only
    adds what's missing). Optional vars are listed, commented out, as hints.
    """
    existing = existing or {}
    lines: list[str] = [
        "# Orchestrator configuration — generated by `orchestrator init`.",
        "# Fill in the blanks, then run `orchestrator doctor` to verify.",
        "",
    ]
    for group in ENV_GROUPS:
        pending = [v for v in group.variables if v.name not in existing]
        if not pending:
            continue
        header = f"# --- {group.name} ---"
        if group.note:
            header += f"  ({group.note})"
        lines.append(header)
        for var in pending:
            if var.hint:
                lines.append(f"# {var.hint}")
            lines.append(f"{var.name}=")
        lines.append("")

    optional_pending = [(n, h) for n, h in _OPTIONAL_HINTS if n not in existing]
    if optional_pending:
        lines.append("# --- Optional ---")
        for name, hint in optional_pending:
            lines.append(f"# {hint}")
            lines.append(f"# {name}=")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def missing_keys(existing: Mapping[str, str]) -> list[str]:
    """Required env vars (from ENV_GROUPS) not present in ``existing``."""
    out: list[str] = []
    for group in ENV_GROUPS:
        for var in group.variables:
            if var.name not in existing:
                out.append(var.name)
    return out


def parse_env_file(text: str) -> dict[str, str]:
    """Minimal ``.env`` parse: ``KEY=value`` lines, ignoring blanks/comments.

    Only the key set matters here (init checks which keys already exist), so
    values are kept verbatim without unquoting.
    """
    env: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key:
            env[key] = value.strip()
    return env


def scaffold_env(path: Path, *, force: bool = False) -> tuple[bool, list[str]]:
    """Write/extend a ``.env`` at ``path``. Returns (wrote_file, keys_added).

    - No file (or ``force``): write a fresh template; ``keys_added`` is every
      required key.
    - Existing file: append only the required keys it's missing, preserving
      everything already there; ``keys_added`` is what was appended (possibly
      empty, in which case nothing is written).
    """
    if path.exists() and not force:
        current = parse_env_file(path.read_text(encoding="utf-8"))
        to_add = missing_keys(current)
        if not to_add:
            return False, []
        snippet = render_env_template(current)
        body = path.read_text(encoding="utf-8").rstrip() + "\n\n" + snippet
        path.write_text(body, encoding="utf-8")
        return True, to_add

    path.write_text(render_env_template({}), encoding="utf-8")
    return True, missing_keys({})


__all__ = [
    "missing_keys",
    "parse_env_file",
    "render_env_template",
    "scaffold_env",
]
