"""Deterministic project scaffolder for greenfield SDLC targets.

When ``resolve_layout`` returns ``mode == "new"``, the feature runner scaffolds a
minimal, runnable project skeleton **before** codegen so generated files land in a
coherent structure (and the project's own ``pytest`` run resolves ``src/``).

No LLM — a fixed template selected by project type (v1 ships Python; the seam
leaves room for others). Idempotent and non-destructive: only missing files are
written, existing files are never clobbered. Safe to call on every feature run.
"""

from __future__ import annotations

import json
import os
import uuid
from pathlib import Path

from orchestrator.catalog.profile import ProjectProfile
from orchestrator.sdlc.layout import TargetLayout

# Project-type GUID for SDK-style C# projects (what `dotnet sln add` writes).
_CSHARP_SLN_PROJECT_TYPE = "9A19103F-16F7-4668-BE54-9A1E7A4F7556"

_PYPROJECT_TEMPLATE = """\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{package}"
version = "0.0.0"
description = "Generated by the SDLC orchestrator."
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8", "pytest-asyncio>=0.24"]

[tool.hatch.build.targets.wheel]
packages = ["{source_dir}"]

[tool.pytest.ini_options]
pythonpath = ["{pythonpath}"]
testpaths = ["{tests_dir}"]
"""

_README_TEMPLATE = """\
# {package}

Project structure scaffolded by the SDLC orchestrator. Source lives in
`{source_dir}/`; tests in `{tests_dir}/`.
"""

_GITIGNORE = """\
__pycache__/
*.py[cod]
.pytest_cache/
.venv/
venv/
build/
dist/
*.egg-info/
.coverage
.mypy_cache/
"""


def scaffold(root: Path | str, layout: TargetLayout, *, profile: ProjectProfile | None = None) -> list[str]:
    """Write the project skeleton for ``layout`` into ``root``, idempotently.

    Returns the worktree-relative paths actually created (empty when everything
    already existed). Never overwrites an existing file — a non-empty repo keeps
    its own ``pyproject``/``README`` while still gaining the package + tests dirs.
    """
    root_path = Path(root)
    _ = profile  # reserved: future template selection beyond language
    if layout.language == "java":
        files = _java_files(layout)
    elif layout.language == "typescript":
        files = _typescript_files(layout)
    elif layout.language == "csharp":
        files = _csharp_files(layout)
    else:
        files = _python_files(layout)

    created: list[str] = []
    for rel, content in files.items():
        path = root_path / rel
        if path.exists():
            continue  # never clobber
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(rel)
    return created


def _python_files(layout: TargetLayout) -> dict[str, str]:
    # ``pythonpath`` parent of the package so ``import <package>`` resolves.
    pythonpath = "src" if layout.src_layout else "."
    return {
        f"{layout.source_dir}/__init__.py": "",
        f"{layout.tests_dir}/__init__.py": "",
        "pyproject.toml": _PYPROJECT_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
            pythonpath=pythonpath,
        ),
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _GITIGNORE,
    }


def _java_files(layout: TargetLayout) -> dict[str, str]:
    group, _, artifact = layout.package_name.rpartition(".")
    return {
        "pom.xml": _POM_TEMPLATE.format(
            group=group or "org.example", artifact=artifact or layout.package_name
        ),
        # Java has no __init__; keep the empty package + test dirs in git.
        f"{layout.source_dir}/.gitkeep": "",
        f"{layout.tests_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _JAVA_GITIGNORE,
    }


def _typescript_files(layout: TargetLayout) -> dict[str, str]:
    # package.json built via json.dumps so it's always valid JSON; the `test`
    # script runs Vitest, which the package manager invokes via `<pm> test`.
    package_json = (
        json.dumps(
            {
                "name": layout.package_name,
                "version": "0.0.0",
                "description": "Generated by the SDLC orchestrator.",
                "type": "module",
                "scripts": {"test": "vitest run"},
                "devDependencies": {
                    "typescript": "^5.4.0",
                    "vitest": "^1.6.0",
                    "@types/node": "^20.0.0",
                },
            },
            indent=2,
        )
        + "\n"
    )
    return {
        "package.json": package_json,
        "tsconfig.json": _TSCONFIG,
        # No __init__/package files in TS; keep the empty source dir in git.
        f"{layout.source_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _TS_GITIGNORE,
    }


def _csharp_files(layout: TargetLayout) -> dict[str, str]:
    # A solution tying an SDK-style classlib (the source project) to an xUnit test
    # project that references it, so `dotnet test` at the root builds + tests both.
    name = layout.package_name
    src_dir, test_dir = layout.source_dir, layout.tests_dir
    test_name = f"{name}.Tests"
    src_csproj = f"{src_dir}/{name}.csproj"
    test_csproj = f"{test_dir}/{test_name}.csproj"
    # ProjectReference from the test project back to the source project (relative).
    ref = os.path.relpath(src_csproj, start=test_dir).replace("/", "\\")
    return {
        f"{name}.sln": _sln(name, src_csproj, test_name, test_csproj),
        src_csproj: _CSPROJ_LIB.format(name=name),
        test_csproj: _CSPROJ_TEST.format(ref=ref),
        # SDK-style projects anchor their own dirs in git; xUnit's default template
        # has no source files, so a placeholder keeps the source dir non-empty.
        f"{src_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _CSHARP_GITIGNORE,
    }


def _sln(name: str, src_csproj: str, test_name: str, test_csproj: str) -> str:
    # Deterministic GUIDs (uuid5) so the same project always scaffolds the same
    # solution — no randomness, reproducible run-to-run. .sln uses backslash paths.
    src_guid = _guid(f"proj:{name}")
    test_guid = _guid(f"proj:{test_name}")
    pt = _CSHARP_SLN_PROJECT_TYPE
    src_path = src_csproj.replace("/", "\\")
    test_path = test_csproj.replace("/", "\\")
    cfgs = "".join(
        f"\t\t{{{g}}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n"
        f"\t\t{{{g}}}.Debug|Any CPU.Build.0 = Debug|Any CPU\n"
        f"\t\t{{{g}}}.Release|Any CPU.ActiveCfg = Release|Any CPU\n"
        f"\t\t{{{g}}}.Release|Any CPU.Build.0 = Release|Any CPU\n"
        for g in (src_guid, test_guid)
    )
    return (
        "Microsoft Visual Studio Solution File, Format Version 12.00\n"
        "# Visual Studio Version 17\n"
        f'Project("{{{pt}}}") = "{name}", "{src_path}", "{{{src_guid}}}"\n'
        "EndProject\n"
        f'Project("{{{pt}}}") = "{test_name}", "{test_path}", "{{{test_guid}}}"\n'
        "EndProject\n"
        "Global\n"
        "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n"
        "\t\tDebug|Any CPU = Debug|Any CPU\n"
        "\t\tRelease|Any CPU = Release|Any CPU\n"
        "\tEndGlobalSection\n"
        "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n"
        f"{cfgs}"
        "\tEndGlobalSection\n"
        f"\tGlobalSection(SolutionProperties) = preSolution\n"
        "\t\tHideSolutionNode = FALSE\n"
        "\tEndGlobalSection\n"
        "EndGlobal\n"
    )


def _guid(seed: str) -> str:
    """A stable upper-case GUID derived from ``seed`` (deterministic, no randomness)."""
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, f"spine-sdlc:{seed}")).upper()


_CSPROJ_LIB = """\
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>{name}</RootNamespace>
  </PropertyGroup>

</Project>
"""

_CSPROJ_TEST = """\
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="{ref}" />
  </ItemGroup>

</Project>
"""

_CSHARP_GITIGNORE = """\
bin/
obj/
*.user
.vs/
[Dd]ebug/
[Rr]elease/
"""


_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
"""

_TS_GITIGNORE = """\
node_modules/
dist/
coverage/
*.tsbuildinfo
.DS_Store
"""


_POM_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>{group}</groupId>
  <artifactId>{artifact}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>
    </plugins>
  </build>
</project>
"""

_JAVA_GITIGNORE = """\
target/
*.class
.gradle/
build/
.idea/
*.iml
"""


__all__ = ["scaffold"]
