"""Deterministic project scaffolder for greenfield SDLC targets.

When ``resolve_layout`` returns ``mode == "new"``, the feature runner scaffolds a
minimal, runnable project skeleton **before** codegen so generated files land in a
coherent structure (and the project's own ``pytest`` run resolves ``src/``).

No LLM — a fixed template selected by project type (v1 ships Python; the seam
leaves room for others). Idempotent and non-destructive: only missing files are
written, existing files are never clobbered. Safe to call on every feature run.
"""

from __future__ import annotations

import json
import os
import re
import uuid
from pathlib import Path

from orchestrator.catalog.profile import ProjectProfile
from orchestrator.sdlc.layout import TargetLayout

# Project-type GUID for SDK-style C# projects (what `dotnet sln add` writes).
_CSHARP_SLN_PROJECT_TYPE = "9A19103F-16F7-4668-BE54-9A1E7A4F7556"
# Greenfield C# target framework when the installed SDK can't be probed (LTS).
_DEFAULT_DOTNET_TFM = "net8.0"

_PYPROJECT_TEMPLATE = """\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{package}"
version = "0.0.0"
description = "Generated by the SDLC orchestrator."
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8", "pytest-asyncio>=0.24"]

[tool.hatch.build.targets.wheel]
packages = ["{source_dir}"]

[tool.pytest.ini_options]
pythonpath = ["{pythonpath}"]
testpaths = ["{tests_dir}"]
"""

_README_TEMPLATE = """\
# {package}

Project structure scaffolded by the SDLC orchestrator. Source lives in
`{source_dir}/`; tests in `{tests_dir}/`.
"""

_GITIGNORE = """\
__pycache__/
*.py[cod]
.pytest_cache/
.venv/
venv/
build/
dist/
*.egg-info/
.coverage
.mypy_cache/
"""


def scaffold(root: Path | str, layout: TargetLayout, *, profile: ProjectProfile | None = None) -> list[str]:
    """Write the project skeleton for ``layout`` into ``root``, idempotently.

    Returns the worktree-relative paths actually created (empty when everything
    already existed). Never overwrites an existing file — a non-empty repo keeps
    its own ``pyproject``/``README`` while still gaining the package + tests dirs.
    """
    root_path = Path(root)
    _ = profile  # reserved: future template selection beyond language
    if layout.language == "java":
        files = _java_files(layout)
    elif layout.language == "typescript":
        files = _typescript_files(layout)
    elif layout.language == "csharp":
        files = _csharp_files(layout)
    elif layout.language == "c":
        files = _c_files(layout)
    elif layout.language == "cpp":
        files = _cpp_files(layout)
    elif layout.language == "go":
        files = _go_files(layout)
    elif layout.language == "sql":
        files = _sql_files(layout)
    else:
        files = _python_files(layout)

    created: list[str] = []
    for rel, content in files.items():
        path = root_path / rel
        if path.exists():
            continue  # never clobber
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(rel)
    if layout.language == "csharp":
        created += _ensure_build_ignores(root_path, ("bin", "obj"))
    elif layout.language in ("c", "cpp"):
        created += _ensure_build_ignores(root_path, ("build",))
    return created


def _ensure_build_ignores(root: Path, dirs: tuple[str, ...]) -> list[str]:
    """Guarantee ``dirs`` (compiled output like ``bin``/``obj`` or CMake ``build``) are
    gitignored so build output never lands in a commit/PR. The scaffold's own
    ``.gitignore`` covers them, but a brownfield or scratch worktree with a pre-existing
    ``.gitignore`` (never clobbered) may not — append the missing rules rather than
    overwrite."""
    gi = root / ".gitignore"
    if not gi.exists():
        return []  # the scaffold just wrote its .gitignore (already has these)
    existing = gi.read_text(encoding="utf-8")
    have = {ln.strip().rstrip("/") for ln in existing.splitlines()}
    missing = [d for d in dirs if d not in have]
    if not missing:
        return []
    sep = "" if existing.endswith("\n") else "\n"
    gi.write_text(
        existing
        + sep
        + "\n# build output (appended by the SDLC scaffold)\n"
        + "".join(f"{d}/\n" for d in missing),
        encoding="utf-8",
    )
    return [".gitignore"]


def _sql_files(layout: TargetLayout) -> dict[str, str]:
    """A greenfield SQL project: an empty, ordered ``migrations/`` directory.

    The generated DDL lands here as ``NNN_<name>.sql``; validation applies the
    folder to an ephemeral database (no build files, no source/test split)."""
    readme = (
        f"# {layout.package_name} — database schema\n\n"
        "Ordered SQL migrations. Each file is applied in filename order "
        "(`001_*.sql`, `002_*.sql`, …). Validated by applying to an ephemeral "
        f"database (dialect: {layout.build_tool}).\n"
    )
    return {
        f"{layout.source_dir}/README.md": readme,
        ".gitignore": _GITIGNORE,
    }


def _python_files(layout: TargetLayout) -> dict[str, str]:
    # ``pythonpath`` parent of the package so ``import <package>`` resolves.
    pythonpath = "src" if layout.src_layout else "."
    return {
        f"{layout.source_dir}/__init__.py": "",
        f"{layout.tests_dir}/__init__.py": "",
        "pyproject.toml": _PYPROJECT_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
            pythonpath=pythonpath,
        ),
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _GITIGNORE,
    }


def _java_files(layout: TargetLayout) -> dict[str, str]:
    group, _, artifact = layout.package_name.rpartition(".")
    return {
        "pom.xml": _POM_TEMPLATE.format(
            group=group or "org.example", artifact=artifact or layout.package_name
        ),
        # Java has no __init__; keep the empty package + test dirs in git.
        f"{layout.source_dir}/.gitkeep": "",
        f"{layout.tests_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _JAVA_GITIGNORE,
    }


def _typescript_files(layout: TargetLayout) -> dict[str, str]:
    # package.json built via json.dumps so it's always valid JSON; the `test`
    # script runs Vitest, which the package manager invokes via `<pm> test`.
    package_json = (
        json.dumps(
            {
                "name": layout.package_name,
                "version": "0.0.0",
                "description": "Generated by the SDLC orchestrator.",
                "type": "module",
                "scripts": {"test": "vitest run"},
                "devDependencies": {
                    "typescript": "^5.4.0",
                    "vitest": "^1.6.0",
                    "@types/node": "^20.0.0",
                },
            },
            indent=2,
        )
        + "\n"
    )
    return {
        "package.json": package_json,
        "tsconfig.json": _TSCONFIG,
        # No __init__/package files in TS; keep the empty source dir in git.
        f"{layout.source_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _TS_GITIGNORE,
    }


def _csharp_files(layout: TargetLayout) -> dict[str, str]:
    # A solution tying an SDK-style classlib (the source project) to an xUnit test
    # project that references it, so `dotnet test` at the root builds + tests both.
    name = layout.package_name
    src_dir, test_dir = layout.source_dir, layout.tests_dir
    test_name = f"{name}.Tests"
    src_csproj = f"{src_dir}/{name}.csproj"
    test_csproj = f"{test_dir}/{test_name}.csproj"
    # Target the installed SDK (set by the runner) so the project runs, not just
    # builds; fall back to the LTS default when unset (unit tests, no SDK probe).
    tfm = layout.target_framework or _DEFAULT_DOTNET_TFM
    # ProjectReference from the test project back to the source project (relative).
    ref = os.path.relpath(src_csproj, start=test_dir).replace("/", "\\")
    return {
        f"{name}.sln": _sln(name, src_csproj, test_name, test_csproj),
        src_csproj: _CSPROJ_LIB.format(name=name, tfm=tfm),
        test_csproj: _CSPROJ_TEST.format(ref=ref, tfm=tfm),
        # SDK-style projects anchor their own dirs in git; xUnit's default template
        # has no source files, so a placeholder keeps the source dir non-empty.
        f"{src_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _CSHARP_GITIGNORE,
    }


def _sln(name: str, src_csproj: str, test_name: str, test_csproj: str) -> str:
    # Deterministic GUIDs (uuid5) so the same project always scaffolds the same
    # solution — no randomness, reproducible run-to-run. .sln uses backslash paths.
    src_guid = _guid(f"proj:{name}")
    test_guid = _guid(f"proj:{test_name}")
    pt = _CSHARP_SLN_PROJECT_TYPE
    src_path = src_csproj.replace("/", "\\")
    test_path = test_csproj.replace("/", "\\")
    cfgs = "".join(
        f"\t\t{{{g}}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n"
        f"\t\t{{{g}}}.Debug|Any CPU.Build.0 = Debug|Any CPU\n"
        f"\t\t{{{g}}}.Release|Any CPU.ActiveCfg = Release|Any CPU\n"
        f"\t\t{{{g}}}.Release|Any CPU.Build.0 = Release|Any CPU\n"
        for g in (src_guid, test_guid)
    )
    return (
        "Microsoft Visual Studio Solution File, Format Version 12.00\n"
        "# Visual Studio Version 17\n"
        f'Project("{{{pt}}}") = "{name}", "{src_path}", "{{{src_guid}}}"\n'
        "EndProject\n"
        f'Project("{{{pt}}}") = "{test_name}", "{test_path}", "{{{test_guid}}}"\n'
        "EndProject\n"
        "Global\n"
        "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n"
        "\t\tDebug|Any CPU = Debug|Any CPU\n"
        "\t\tRelease|Any CPU = Release|Any CPU\n"
        "\tEndGlobalSection\n"
        "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n"
        f"{cfgs}"
        "\tEndGlobalSection\n"
        f"\tGlobalSection(SolutionProperties) = preSolution\n"
        "\t\tHideSolutionNode = FALSE\n"
        "\tEndGlobalSection\n"
        "EndGlobal\n"
    )


def _guid(seed: str) -> str:
    """A stable upper-case GUID derived from ``seed`` (deterministic, no randomness)."""
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, f"spine-sdlc:{seed}")).upper()


_CSPROJ_LIB = """\
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>{tfm}</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>{name}</RootNamespace>
  </PropertyGroup>

</Project>
"""

_CSPROJ_TEST = """\
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>{tfm}</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="{ref}" />
  </ItemGroup>

</Project>
"""

_CSHARP_GITIGNORE = """\
bin/
obj/
*.user
.vs/
[Dd]ebug/
[Rr]elease/
"""


def _c_files(layout: TargetLayout) -> dict[str, str]:
    # A CMake project that globs src/*.c into a library and turns each tests/*.c into a
    # ctest executable linked against it. A stub source + header give CMake something to
    # configure before codegen; tests run via `ctest` with plain assert()-based mains
    # (no external framework needed — buildable offline).
    name = layout.package_name
    guard = f"{name.upper()}_H"
    cmake = _CMAKELISTS.replace("__name__", name)
    header = _C_HEADER.replace("__guard__", guard).replace("__name__", name)
    return {
        "CMakeLists.txt": cmake,
        f"{layout.source_dir}/{name}.h": header,
        f"{layout.source_dir}/{name}.c": f'#include "{name}.h"\n',
        f"{layout.tests_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _C_GITIGNORE,
    }


_CMAKELISTS = """\
cmake_minimum_required(VERSION 3.15)
project(__name__ C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Library built from everything under src/.
file(GLOB __name___SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/src/*.c")
add_library(__name__ ${__name___SOURCES})
target_include_directories(__name__ PUBLIC "${CMAKE_SOURCE_DIR}/src")

# Tests: each tests/*.c is a ctest executable linked against the library.
enable_testing()
file(GLOB __name___TESTS CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/tests/*.c")
foreach(test_file ${__name___TESTS})
    get_filename_component(test_name ${test_file} NAME_WE)
    add_executable(${test_name} ${test_file})
    target_link_libraries(${test_name} __name__)
    add_test(NAME ${test_name} COMMAND ${test_name})
endforeach()
"""

_C_HEADER = """\
#ifndef __guard__
#define __guard__

/* Public API for __name__. Declare functions here; define them in __name__.c. */

#endif /* __guard__ */
"""

_C_GITIGNORE = """\
build/
*.o
*.a
*.so
*.dylib
compile_commands.json
"""


def _cpp_files(layout: TargetLayout) -> dict[str, str]:
    # A CMake (CXX) project: src/*.cpp glob into a library, each tests/*.cpp into a
    # ctest executable (assert-based main, offline — no Catch2/GTest fetch needed).
    name = layout.package_name
    guard = f"{name.upper()}_HPP"
    cmake = _CMAKELISTS_CPP.replace("__name__", name)
    header = _CPP_HEADER.replace("__guard__", guard).replace("__name__", name)
    return {
        "CMakeLists.txt": cmake,
        f"{layout.source_dir}/{name}.hpp": header,
        f"{layout.source_dir}/{name}.cpp": f'#include "{name}.hpp"\n',
        f"{layout.tests_dir}/.gitkeep": "",
        "README.md": _README_TEMPLATE.format(
            package=layout.package_name,
            source_dir=layout.source_dir,
            tests_dir=layout.tests_dir,
        ),
        ".gitignore": _C_GITIGNORE,
    }


_CMAKELISTS_CPP = """\
cmake_minimum_required(VERSION 3.15)
project(__name__ CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Library built from everything under src/.
file(GLOB __name___SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/src/*.cpp")
add_library(__name__ ${__name___SOURCES})
target_include_directories(__name__ PUBLIC "${CMAKE_SOURCE_DIR}/src")

# Tests: each tests/*.cpp is a ctest executable linked against the library.
enable_testing()
file(GLOB __name___TESTS CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/tests/*.cpp")
foreach(test_file ${__name___TESTS})
    get_filename_component(test_name ${test_file} NAME_WE)
    add_executable(${test_name} ${test_file})
    target_link_libraries(${test_name} __name__)
    add_test(NAME ${test_name} COMMAND ${test_name})
endforeach()
"""

_CPP_HEADER = """\
#ifndef __guard__
#define __guard__

// Public API for __name__. Declare classes/functions here; define them in __name__.cpp.

#endif  // __guard__
"""


def _go_ident(module: str) -> str:
    """The Go ``package`` identifier for a module path (its last element, lowercased)."""
    last = module.rstrip("/").rsplit("/", 1)[-1]
    ident = re.sub(r"[^0-9a-zA-Z_]", "", last).lower() or "app"
    return f"p{ident}" if ident[0].isdigit() else ident


def _go_files(layout: TargetLayout) -> dict[str, str]:
    # A minimal single-package Go module: go.mod at the root + a stub source file
    # declaring the package, so `go build ./...` / `go test ./...` are green before
    # codegen (a package with no tests is still an `ok` run). Tests are co-located
    # (`<name>_test.go` beside the code), so there is no separate tests dir.
    module = layout.package_name
    pkg = _go_ident(module)
    src = layout.source_dir
    stub = f"{pkg}.go" if src == "." else f"{src}/{pkg}.go"
    return {
        "go.mod": f"module {module}\n\ngo 1.21\n",
        stub: f"// Package {pkg} is scaffolded by the SDLC orchestrator.\npackage {pkg}\n",
        "README.md": _README_TEMPLATE.format(package=module, source_dir=src, tests_dir=layout.tests_dir),
        ".gitignore": _GO_GITIGNORE,
    }


_GO_GITIGNORE = """\
# Binaries / test artifacts
*.exe
*.test
*.out
# Go workspace
go.work
go.work.sum
"""


_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
"""

_TS_GITIGNORE = """\
node_modules/
dist/
coverage/
*.tsbuildinfo
.DS_Store
"""


_POM_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>{group}</groupId>
  <artifactId>{artifact}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>
    </plugins>
  </build>
</project>
"""

_JAVA_GITIGNORE = """\
target/
*.class
.gradle/
build/
.idea/
*.iml
"""


__all__ = ["scaffold"]
