"""Render the persisted backlog as a human-readable BACKLOG.md with progress.

The cache JSON is the source of truth (specs + ``--intent`` resolution); this
module is the *view*: a checkbox list of intents with a status marker each
(``[ ]`` todo, ``[~]`` in progress, ``[x]`` done) plus the issue/PR that built
it. Pure rendering + a thin file writer — no extraction, no LLM.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from orchestrator.intake.service import BacklogPlan

_MARKERS = {"todo": "[ ]", "in_progress": "[~]", "done": "[x]"}
_DEFAULT_BACKLOG = "BACKLOG.md"


def backlog_path() -> Path:
    """Local canonical backlog path (``$ORCHESTRATOR_BACKLOG_PATH`` or ./BACKLOG.md)."""
    return Path(os.getenv("ORCHESTRATOR_BACKLOG_PATH", _DEFAULT_BACKLOG))


def render_markdown(source: str, plan: BacklogPlan, progress: dict[str, dict[str, Any]]) -> str:
    """Render the backlog + progress as markdown."""
    statuses = [progress.get(i.id, {}).get("status", "todo") for i in plan.intents]
    done = statuses.count("done")
    in_progress = statuses.count("in_progress")
    total = len(plan.intents)

    lines = [
        f"# Backlog — {source}",
        "<!-- generated by orchestrator; the cache JSON is source of truth, edits here are advisory -->",
        "",
        f"**Progress:** {done} / {total} done · {in_progress} in progress",
        "",
    ]
    for intent in plan.intents:
        entry = progress.get(intent.id, {})
        marker = _MARKERS.get(entry.get("status", "todo"), "[ ]")
        notes = [str(entry[k]) for k in ("issue_key", "pr_url") if entry.get(k)]
        suffix = f"  ({' · '.join(notes)})" if notes else ""
        lines.append(f"- {marker} `{intent.id}` — {intent.title}{suffix}")
    return "\n".join(lines) + "\n"


def write_backlog(
    path: Path | str, source: str, plan: BacklogPlan, progress: dict[str, dict[str, Any]]
) -> Path:
    """Render and write BACKLOG.md to ``path``."""
    target = Path(path)
    if target.parent != Path(""):
        target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_markdown(source, plan, progress), encoding="utf-8")
    return target


__all__ = ["backlog_path", "render_markdown", "write_backlog"]
