"""Deterministic knowledge-base renderers: PKG facts + profile → markdown.

Pure functions, no LLM. Each returns a markdown document (or an empty-state note
for a greenfield repo). The PKG is the canonical source; these are the legible,
committed view.

Every symbol named here deep-links to its definition (``provenance`` → a relative
``file#Lline`` link) so a reader can click through instead of leaving to grep, and
relationships render from *both* ends — a hotspot lists its callers, each of which
is itself a link. Output must stay **diff-stable**: these files are committed, so
a regeneration with no code change has to produce a zero-line diff. That means
every list is totally sorted; never rely on graph/edge iteration order.
"""

from __future__ import annotations

import hashlib
import re
from collections import defaultdict
from pathlib import Path
from urllib.parse import quote

from orchestrator.catalog.profile import ProjectProfile
from orchestrator.knowledge.areas import AreaIndex, area_of_name, zone_of
from orchestrator.pkg.facts import EdgeKind, Node, NodeKind
from orchestrator.pkg.stats import GraphStats
from orchestrator.pkg.store import FactStore

# How many callers to list under a hotspot on architecture.md before eliding. That page
# is orientation; the module page below is where the fuller list lives.
_MAX_CALLERS = 5

# The module page is the detail view, so it lists far more before eliding — "+N more" is
# itself a dead end, and this page exists precisely to be the end of that walk.
_MAX_CALLERS_PAGE = 25

# How many modules get their own page. A page each is not survivable at real scale
# (this repo: 530 first-party modules; open5gs: 8.6k files) — the tail is listed on
# architecture.md instead, and the cut is always reported (principle 5).
MAX_MODULE_PAGES = 50

# Symbols listed on one module page before eliding. Generous: listing a module's
# symbols is the page's whole job, and most modules are far under this.
_MAX_SYMBOLS_PER_PAGE = 100

MODULES_SUBDIR = "modules"
AREAS_SUBDIR = "areas"
ENTITIES_SUBDIR = "entities"

# Entity pages. A schema with hundreds of tables is real; cap and report like the rest.
MAX_ENTITY_PAGES = 50

# Hotspots shown, and how deep to look for them. Each shown hotspot costs an `impact_of`
# BFS over callers — the one genuinely expensive render (~0.8s for 10 on a 981-module
# repo), which is why it is bounded here and not offered per-symbol on every module page.
# The candidate pool is much deeper than the display count because most top-ranked symbols
# are third-party and get filtered out.
_BLAST_RADIUS_HOTSPOTS = 10
HOTSPOT_CANDIDATES = 200

# Areas get pages too. Far fewer than modules by construction (an area is a coarse
# component), but a huge repo can still sprawl — cap and report.
MAX_AREA_PAGES = 25

# Neighbours drawn on an area's scoped diagram. The whole trick of a per-page diagram is
# that it is SCOPED: the repo-wide map needs a hard cap to stay readable, this doesn't.
_MAX_DIAGRAM_NEIGHBOURS = 8

_HEADER = (
    "<!-- generated by `orchestrator understand`; the PKG is source of truth, edits here are advisory -->"
)

_GREENFIELD_NOTE = (
    "> **Greenfield** — little or no source yet. This will fill in as features land "
    "(re-run `orchestrator understand` or it refreshes each `sdlc feature` run)."
)


def _doc(title: str, body: str) -> str:
    return f"# {title}\n{_HEADER}\n\n{body.rstrip()}\n"


def _is_test_module(name: str) -> bool:
    return (
        name == "tests"
        or name.startswith(("tests.", "test_"))
        or ".tests." in name
        or name.endswith(".conftest")
    )


def _under_tests(node: object) -> bool:
    prov = getattr(node, "provenance", None)
    f = getattr(prov, "file", "") if prov else ""
    return f.startswith(("tests/", "test/")) or "/tests/" in f or "/test/" in f


def _link(node: Node, src: str | None, *, label: str | None = None) -> str:
    """A node as a source deep-link, degrading to plain text when it can't be one.

    ``src`` is the relative path from this document back to the repo root, or
    ``None`` when the bank lives outside the repo — in which case a link would be
    broken or machine-specific, so we render the location as text instead. An
    external node (no provenance) has no definition to point at.
    """
    text = label or node.name
    prov = node.provenance
    if prov is None:
        return f"`{text}`"
    if src is None:
        # Parenthetical, not a dash: these render mid-sentence ("- X — 2 types"),
        # and a second em-dash there is unreadable.
        return f"`{text}` (`{prov.file}:{prov.line}`)"
    return f"[`{text}`]({src}{quote(prov.file)}#L{prov.line})"


def _caller_line(store: FactStore, node_id: str, src: str | None) -> str:
    """The 'called by' backlink line for a hotspot — the other half of the edge.

    Sorted by (name, id): ``callers_of`` returns edge order, which is extraction
    order, which would churn the diff on every unrelated code change.
    """
    seen: dict[str, Node] = {cs.caller.id: cs.caller for cs in store.callers_of(node_id)}
    callers = sorted(seen.values(), key=lambda n: (n.name, n.id))
    if not callers:
        return ""
    shown = ", ".join(_link(c, src) for c in callers[:_MAX_CALLERS])
    rest = len(callers) - _MAX_CALLERS
    more = f", +{rest} more" if rest > 0 else ""
    return f"\n  - called by {shown}{more}"


def _slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.")
    return s[:80] or "module"


def module_page_slugs(names: list[str]) -> dict[str, str]:
    """Module name → unique page stem.

    Names become filenames and they are wild across the front-ends: dotted namespaces
    (``App.Api``), paths (``src/smf/smf-sm.c``), symbols (``cpp:A::A``). Collisions are
    resolved with a short digest of the full name, and checked **case-folded** — macOS
    and Windows filesystems are case-insensitive, so ``Foo.md`` and ``foo.md`` would
    silently clobber each other. Assignment walks sorted names, so the mapping is
    identical run to run (principle 4).
    """
    out: dict[str, str] = {}
    used: set[str] = set()
    for name in sorted(names):
        stem = _slug(name)
        if stem.lower() in used:
            stem = f"{stem}-{hashlib.sha1(name.encode()).hexdigest()[:6]}"
        used.add(stem.lower())
        out[name] = stem
    return out


def select_module_pages(store: FactStore, *, limit: int = MAX_MODULE_PAGES) -> list[Node]:
    """The first-party modules worth a page, biggest first (ties broken by name).

    Capped: a page per module is not survivable at real scale, and an unbounded
    page set would bury the reader as surely as no pages at all.
    """
    mods = [
        n for n in store.nodes if n.kind is NodeKind.MODULE and not n.external and not _is_test_module(n.name)
    ]
    sized: list[tuple[Node, int]] = []
    for m in mods:
        members = sum(1 for c in store.children_of(m.id) if c.kind in (NodeKind.TYPE, NodeKind.FUNCTION))
        if members:
            sized.append((m, members))
    sized.sort(key=lambda t: (-t[1], t[0].name))
    return [m for m, _ in sized[:limit]]


class ModuleDeps:
    """The module-level import graph, resolved once.

    **IMPORTS edges target the imported *symbol*, not the module** — the Python
    front-end emits ``py:web.views -> py:app.core.slugify``. So a module's importers are
    *always empty* if you ask ``importers_of(module_id)``: nothing ever points at a module
    id. Both endpoints have to be walked up to their owning module (the CONTAINS walk in
    ``AreaIndex``) before there is a module→module edge to render at all.
    """

    def __init__(self, store: FactStore, index: AreaIndex) -> None:
        self.imports: dict[str, set[str]] = defaultdict(set)
        self.importers: dict[str, set[str]] = defaultdict(set)
        for edge in store.edges_of_kind(EdgeKind.IMPORTS):
            src_node, dst_node = store.node(edge.src), store.node(edge.dst)
            if src_node is None or dst_node is None:
                continue
            src_mod, dst_mod = index.module_of(src_node), index.module_of(dst_node)
            if src_mod is None or dst_mod is None or src_mod.id == dst_mod.id:
                continue
            self.imports[src_mod.id].add(dst_mod.id)
            self.importers[dst_mod.id].add(src_mod.id)


def _symbol_section(store: FactStore, sym: Node, src: str | None) -> list[str]:
    """One symbol as an anchorable subsection: definition, who calls it, what it calls.

    The heading is what makes ``modules/foo.md#normalize`` addressable — symbols get
    anchors, not files (a file per symbol does not survive a 10k-node graph).
    """
    out = [f"### `{sym.name}`", ""]
    prov = sym.provenance
    if prov is not None:
        loc = f"{prov.file}:{prov.line}"
        out.append(f"`{loc}`" if src is None else f"[`{loc}`]({src}{quote(prov.file)}#L{prov.line})")
        out.append("")

    for title, nodes in (
        ("Called by", [c.caller for c in store.callers_of(sym.id)]),
        ("Calls", store.callees_of(sym.id)),
    ):
        uniq = sorted({n.id: n for n in nodes}.values(), key=lambda n: (n.name, n.id))
        if not uniq:
            continue
        shown = ", ".join(_link(n, src) for n in uniq[:_MAX_CALLERS_PAGE])
        rest = len(uniq) - _MAX_CALLERS_PAGE
        out.append(f"- **{title}** ({len(uniq)}): {shown}" + (f", +{rest} more" if rest > 0 else ""))

    fields = sorted(c.name for c in store.children_of(sym.id) if c.kind is NodeKind.FIELD)
    if fields:
        out.append("- **Fields**: " + ", ".join(f"`{f}`" for f in fields))

    out.append("")
    return out


def _module_dep_section(
    store: FactStore, module: Node, page_of: dict[str, str], src: str | None, deps: ModuleDeps
) -> list[str]:
    """Imports and imported-by — the dependency edge rendered from both ends.

    Reads the resolved module→module graph, not raw IMPORTS edges: those point at the
    imported symbol, so asking the edges directly renders "imports `slugify`" (a symbol,
    not a dependency) and an always-empty "Imported by".

    A sibling that has its own page links to it; one that doesn't degrades to its name.
    Never link to a page we didn't write.
    """
    out: list[str] = []
    for title, ids in (
        ("Imports", deps.imports.get(module.id, set())),
        ("Imported by", deps.importers.get(module.id, set())),
    ):
        nodes = [n for n in (store.node(i) for i in ids) if n is not None]
        uniq = sorted(nodes, key=lambda n: (n.name, n.id))
        if not uniq:
            continue
        rendered = [f"[`{n.name}`]({page_of[n.id]}.md)" if n.id in page_of else _link(n, src) for n in uniq]
        out += [f"## {title}", "", ", ".join(rendered), ""]
    return out


def render_module_page(
    store: FactStore, module: Node, *, src: str | None, page_of: dict[str, str], deps: ModuleDeps
) -> str:
    """One module's page: every symbol it owns, anchored, with its call edges both ways.

    ``src`` is the path from ``episteme/modules/`` back to the repo root (one level
    deeper than the top-level docs); ``page_of`` maps module id → page stem for the
    modules that actually got one; ``deps`` is the resolved module→module import graph.
    """
    children = store.children_of(module.id)
    types = sorted((c for c in children if c.kind is NodeKind.TYPE), key=lambda n: (n.name, n.id))
    funcs = sorted((c for c in children if c.kind is NodeKind.FUNCTION), key=lambda n: (n.name, n.id))

    head = ["[← Episteme](../README.md) · [Architecture](../architecture.md)", ""]
    prov = module.provenance
    if prov is not None:
        loc = prov.file
        head.append(f"**Source:** `{loc}`" if src is None else f"**Source:** [`{loc}`]({src}{quote(loc)})")
    # One line, assembled before appending — these are joined with "\n", so appending
    # the language separately would drop it onto a line of its own.
    counts = f"{len(types)} types · {len(funcs)} functions"
    if module.language:
        counts += f" · {module.language}"
    head += ["", counts, ""]

    body = list(head)
    budget = _MAX_SYMBOLS_PER_PAGE
    for title, syms in (("Types", types), ("Functions", funcs)):
        if not syms:
            continue
        body += [f"## {title}", ""]
        for sym in syms[:budget]:
            body += _symbol_section(store, sym, src)
        elided = len(syms) - budget
        if elided > 0:
            body.append(f"_+{elided} more {title.lower()} not shown (see the graph)._\n")
        budget = max(0, budget - len(syms))

    body += _module_dep_section(store, module, page_of, src, deps)
    return _doc(f"`{module.name}`", "\n".join(body).rstrip())


class DataLayer:
    """Who reads and writes each entity, indexed once.

    ``store`` answers the FK questions (``references_of`` / ``dependents_of``) but has no
    query for READS/WRITES, so index them here — same shape as ``ModuleDeps``: aggregate
    the whole graph once rather than rescan every edge per entity.
    """

    def __init__(self, store: FactStore) -> None:
        self.readers: dict[str, set[str]] = defaultdict(set)
        self.writers: dict[str, set[str]] = defaultdict(set)
        for e in store.edges_of_kind(EdgeKind.READS):
            self.readers[e.dst].add(e.src)
        for e in store.edges_of_kind(EdgeKind.WRITES):
            self.writers[e.dst].add(e.src)


def _field_label(field: Node, entity: Node) -> str:
    """A field's own name. Field ids/names are table-qualified (``customers.id``), so
    rendering them raw under their own table repeats the table on every line."""
    prefix = f"{entity.name}."
    return field.name[len(prefix) :] if field.name.startswith(prefix) else field.name


def select_entity_pages(store: FactStore, *, limit: int = MAX_ENTITY_PAGES) -> list[Node]:
    """The entities worth a page — most-connected first, ties broken by name."""
    entities = [n for n in store.nodes if n.kind is NodeKind.ENTITY]
    ranked = sorted(
        entities,
        key=lambda e: (
            -(len(store.references_of(e.id)) + len(store.dependents_of(e.id))),
            e.name,
        ),
    )
    return ranked[:limit]


def render_entity_page(
    store: FactStore,
    entity: Node,
    *,
    src: str | None,
    entity_pages: dict[str, str],
    data: DataLayer,
) -> str:
    """One table: its columns, its foreign keys **both ways**, and the code that touches it.

    "Referenced by" is the half that was missing entirely: `references_of` answers what
    *this* table points at, and a reader looking at `customers` needs the opposite — which
    tables depend on it, i.e. what a change here can break.
    """
    fields = sorted(
        (c for c in store.children_of(entity.id) if c.kind is NodeKind.FIELD),
        key=lambda n: (n.name, n.id),
    )
    refs = sorted(store.references_of(entity.id), key=lambda n: (n.name, n.id))
    deps = sorted(store.dependents_of(entity.id), key=lambda n: (n.name, n.id))

    body = ["[← Episteme](../README.md) · [Domain model](../domain-model.md)", ""]
    prov = entity.provenance
    if prov is not None:
        loc = f"{prov.file}:{prov.line}"
        body.append(
            f"**Defined in:** `{loc}`"
            if src is None
            else f"**Defined in:** [`{loc}`]({src}{quote(prov.file)}#L{prov.line})"
        )
        body.append("")

    body.append(
        f"{len(fields)} field{'s' if len(fields) != 1 else ''} · "
        f"references {len(refs)} · referenced by {len(deps)}"
    )
    body.append("")

    if fields:
        body += ["## Fields", ""]
        body += [f"- `{_field_label(f, entity)}`" for f in fields]
        body.append("")

    def _ent_link(n: Node) -> str:
        return f"[`{n.name}`]({entity_pages[n.id]}.md)" if n.id in entity_pages else f"`{n.name}`"

    for title, nodes, note in (
        ("References", refs, "tables this one points at (foreign keys out)"),
        ("Referenced by", deps, "tables that depend on this one — a change here reaches them"),
    ):
        if not nodes:
            continue
        body += [f"## {title}", "", f"_{note}_", "", ", ".join(_ent_link(n) for n in nodes), ""]

    for title, ids in (
        ("Read by", data.readers.get(entity.id, set())),
        ("Written by", data.writers.get(entity.id, set())),
    ):
        nodes = [n for n in (store.node(i) for i in ids) if n is not None]
        if not nodes:
            continue
        rendered = [_link(n, src) for n in sorted(nodes, key=lambda n: (n.name, n.id))]
        body += [f"## {title}", "", ", ".join(rendered), ""]

    return _doc(f"`{entity.name}`", "\n".join(body).rstrip())


class AreaFacts:
    """One area's shape, collected once so the prose and the diagram agree."""

    def __init__(self, name: str, modules: list[Node]) -> None:
        self.name = name
        self.zone = zone_of(name)
        self.modules = sorted(modules, key=lambda n: (n.name, n.id))
        self.types = 0
        self.functions = 0
        self.imports: set[str] = set()  # areas this one depends on
        self.importers: set[str] = set()  # areas that depend on this one

    @property
    def size(self) -> int:
        return self.types + self.functions


def collect_areas(store: FactStore, deps: ModuleDeps) -> dict[str, AreaFacts]:
    """Group first-party modules into areas and lift the import graph to area→area.

    Self-edges are dropped: an area importing itself is noise, not architecture. Edges to
    modules outside the first-party set (third-party, tests) are dropped too — this is a
    map of *this* project's components.
    """
    areas: dict[str, AreaFacts] = {}
    area_of_module: dict[str, str] = {}
    for mod in store.nodes:
        if mod.kind is not NodeKind.MODULE or mod.external or _is_test_module(mod.name):
            continue
        name = area_of_name(mod.name)
        area_of_module[mod.id] = name
        areas.setdefault(name, AreaFacts(name, [])).modules.append(mod)

    for name, area in areas.items():
        area.modules.sort(key=lambda n: (n.name, n.id))
        for mod in area.modules:
            for child in store.children_of(mod.id):
                if child.kind is NodeKind.TYPE:
                    area.types += 1
                elif child.kind is NodeKind.FUNCTION:
                    area.functions += 1
            for dep_id in deps.imports.get(mod.id, set()):
                other = area_of_module.get(dep_id)
                if other and other != name:
                    area.imports.add(other)
            for dep_id in deps.importers.get(mod.id, set()):
                other = area_of_module.get(dep_id)
                if other and other != name:
                    area.importers.add(other)
    return areas


def select_area_pages(areas: dict[str, AreaFacts], *, limit: int = MAX_AREA_PAGES) -> list[AreaFacts]:
    """The areas worth a page, biggest first (ties broken by name)."""
    ranked = sorted((a for a in areas.values() if a.size), key=lambda a: (-a.size, a.name))
    return ranked[:limit]


def _area_prose(area: AreaFacts, total_areas: int) -> str:
    """The derived 'what this is' — templated from facts, no LLM, no network.

    This is the deterministic tier: it states what the graph knows (size, role, who
    depends on it) and never guesses at intent. Prose that *explains why* is a separate,
    opt-in tier — it must never become a hard dependency of this one, or regenerating the
    episteme would need an API key, and a knowledge base that can't be regenerated rots.
    """
    what = (
        f"**`{area.name}`** is one of {total_areas} areas in this repo, "
        f"in the `{area.zone}` zone. It holds {len(area.modules)} "
        f"module{'s' if len(area.modules) != 1 else ''} — {area.types} types and "
        f"{area.functions} functions."
    )
    if area.importers and area.imports:
        role = (
            f"It sits in the middle of the graph: {len(area.imports)} "
            f"area{'s' if len(area.imports) != 1 else ''} below it, "
            f"{len(area.importers)} above. Changes here can reach both ways."
        )
    elif area.importers:
        role = (
            f"Nothing here depends on other areas, but {len(area.importers)} "
            f"area{'s' if len(area.importers) != 1 else ''} depend{'s' if len(area.importers) == 1 else ''} "
            "on it — it's a foundation, so changes ripple outward."
        )
    elif area.imports:
        role = (
            f"No other area imports it, and it draws on {len(area.imports)} — "
            "it's a leaf, so it's the safer place to change."
        )
    else:
        role = "It has no import edges to or from other areas — it stands alone."
    return f"{what} {role}"


def _mermaid_id(name: str, i: int) -> str:
    """A mermaid-safe node id. Positional, so it can't collide and can't leak punctuation."""
    return f"n{i}"


def _area_diagram(area: AreaFacts, page_of: dict[str, str]) -> list[str]:
    """This area and its immediate neighbours, plus a linked legend.

    Scoped on purpose: the repo-wide map in `state` needs a hard 18-node cap to stay
    readable *because it draws everything*. Here we draw one area and its neighbours —
    small enough to read without a cap fighting us.

    **No `click` directives.** GitHub renders mermaid with securityLevel=strict and offers
    no way to loosen it, so `click` does nothing there — and can make GitHub refuse the
    diagram entirely ("This content is blocked"). The legend below the diagram does the
    navigating instead; it works everywhere markdown does.
    """
    ins = sorted(area.importers)[:_MAX_DIAGRAM_NEIGHBOURS]
    outs = sorted(area.imports)[:_MAX_DIAGRAM_NEIGHBOURS]
    if not ins and not outs:
        return []

    # An area can be both an importer and an import (a mutual dependency), so dedupe
    # before declaring nodes — otherwise it gets two node lines and two legend entries.
    # The two *edges* are kept: a cycle pointing both ways is a real fact worth seeing.
    neighbours: list[str] = []
    for other in ins + outs:
        if other not in neighbours:
            neighbours.append(other)
    ids = {name: _mermaid_id(name, i) for i, name in enumerate(neighbours, start=1)}

    def _label(name: str) -> str:
        # Quoted labels tolerate dots/slashes; a stray quote would break the parse.
        return name.replace('"', "'")

    out = ["```mermaid", "flowchart LR"]
    out.append(f'  n0["{_label(area.name)}"]')
    for other in neighbours:
        out.append(f'  {ids[other]}["{_label(other)}"]')
    for other in ins:
        out.append(f"  {ids[other]} --> n0")
    for other in outs:
        out.append(f"  n0 --> {ids[other]}")
    out += ["```", ""]

    legend = [f"**`{area.name}`** (this area)"]
    legend += [
        f"[`{other}`]({page_of[other]}.md)" if other in page_of else f"`{other}`" for other in neighbours
    ]
    out += ["**In the diagram:** " + " · ".join(legend), ""]
    if len(area.importers) > len(ins) or len(area.imports) > len(outs):
        shown, total = len(ins) + len(outs), len(area.importers) + len(area.imports)
        out += [f"_Showing {shown} of {total} neighbouring areas._", ""]
    return out


def render_area_page(
    area: AreaFacts,
    *,
    total_areas: int,
    src: str | None,
    area_pages: dict[str, str],
    module_pages: dict[str, str],
) -> str:
    """One area: what it is, the picture, its modules, and its neighbours both ways."""
    body = [
        "[← Episteme](../README.md) · [Architecture](../architecture.md)",
        "",
        _area_prose(area, total_areas),
        "",
    ]
    body += _area_diagram(area, area_pages)

    body += ["## Modules", ""]
    for mod in area.modules:
        if mod.id in module_pages:
            link = f"[`{mod.name}`](../{MODULES_SUBDIR}/{module_pages[mod.id]}.md)"
        else:
            link = _link(mod, src)
        body.append(f"- {link}")
    body.append("")

    for title, names in (("Depends on", sorted(area.imports)), ("Depended on by", sorted(area.importers))):
        if not names:
            continue
        rendered = [f"[`{n}`]({area_pages[n]}.md)" if n in area_pages else f"`{n}`" for n in names]
        body += [f"## {title}", "", ", ".join(rendered), ""]

    return _doc(f"`{area.name}`", "\n".join(body).rstrip())


def render_tech_context(profile: ProjectProfile, *, greenfield: bool) -> str:
    langs = ", ".join(sorted(profile.languages)) or "—"
    rows = [
        ("Languages", langs),
        ("Framework", profile.framework or "—"),
        ("Database", "yes" if profile.has_db else "no"),
        ("Migrations", "yes" if profile.has_migrations else "no"),
        ("Test runner", profile.test_runner or "—"),
        ("Task type (default)", profile.task_type),
    ]
    table = "| Aspect | Value |\n|---|---|\n" + "\n".join(f"| {k} | {v} |" for k, v in rows)
    body = (_GREENFIELD_NOTE + "\n\n" if greenfield else "") + table
    return _doc("Tech context", body)


def render_architecture(
    store: FactStore,
    stats: GraphStats,
    *,
    greenfield: bool,
    src: str | None = None,
    page_of: dict[str, str] | None = None,
    areas: list[AreaFacts] | None = None,
    area_pages: dict[str, str] | None = None,
) -> str:
    """Architecture overview — the top of the walk.

    ``src`` is the relative path from this document to the repo root, enabling source
    deep-links; ``None`` renders locations as plain text. ``page_of`` maps module id →
    page stem: a module with a page links *down* to it (the page carries the detail),
    one without links straight to its source. ``areas`` + ``area_pages`` add the coarser
    component level above modules.
    """
    pages = page_of or {}
    apages = area_pages or {}
    if greenfield or stats.total_nodes == 0:
        return _doc("Architecture", _GREENFIELD_NOTE)

    counts = "\n".join(
        f"- {kind.value}: {n}"
        for kind, n in sorted(stats.node_counts.items(), key=lambda kv: (-kv[1], kv[0].value))
        if n
    )

    # Module map: first-party SOURCE modules (tests excluded) and their members (top 25).
    modules = {
        n.id: n
        for n in store.nodes
        if n.kind is NodeKind.MODULE and not n.external and not _is_test_module(n.name)
    }
    members: dict[str, dict[str, int]] = defaultdict(lambda: {"Type": 0, "Function": 0})
    for mod_id in modules:
        for child in store.children_of(mod_id):
            if child.kind is NodeKind.TYPE:
                members[mod_id]["Type"] += 1
            elif child.kind is NodeKind.FUNCTION:
                members[mod_id]["Function"] += 1
    # Tie-break on name: size alone leaves equal-sized modules in dict order, which
    # reshuffles this list whenever unrelated code moves. Committed docs must diff clean.
    ranked = sorted(
        ((mid, c) for mid, c in members.items() if c["Type"] or c["Function"]),
        key=lambda kv: (-(kv[1]["Type"] + kv[1]["Function"]), modules[kv[0]].name),
    )[:25]

    def _map_link(mid: str) -> str:
        mod = modules[mid]
        if mid in pages:
            return f"[`{mod.name}`]({MODULES_SUBDIR}/{pages[mid]}.md)"
        return _link(mod, src)

    module_lines = (
        "\n".join(f"- {_map_link(mid)} — {c['Type']} types, {c['Function']} functions" for mid, c in ranked)
        or "- (no first-party modules with members)"
    )
    shown, total = len(ranked), sum(1 for c in members.values() if c["Type"] or c["Function"])
    if total > shown:
        module_lines += f"\n\n_Showing the {shown} biggest of {total} first-party modules._"

    # Rank by call count, but only over code this project owns. Raw `top_called_functions`
    # is dominated by stdlib/third-party symbols called from tests — on this repo the top
    # entries were `pytest.raises`, `json.dumps`, `httpx.AsyncClient`, `os.getenv`. A blast
    # radius for `json.dumps` is worse than noise: you cannot change it, so it crowds out
    # the code you can. Externals have no provenance (`grounded` is False); test helpers
    # are excluded the same way the module map excludes them.
    first_party = [
        f
        for f in stats.top_called_functions
        if (n := store.node(f.node_id)) is not None and n.grounded and not _under_tests(n)
    ]
    hot: list[str] = []
    for f in first_party[:_BLAST_RADIUS_HOTSPOTS]:
        node = store.node(f.node_id)
        label = _link(node, src) if node is not None else f"`{f.name}`"
        # Blast radius: not just who calls it, but everything a change here can reach,
        # transitively. `call_count` is direct callers only and understates the risk.
        reach = store.impact_of(f.node_id)
        radius = ""
        if reach:
            hops = max(d for _, d in reach)
            radius = f" · **reaches {len(reach)} symbols** (≤{hops} hop{'s' if hops != 1 else ''})"
        hot.append(f"- {label} — {f.call_count} call-sites{radius}{_caller_line(store, f.node_id, src)}")
    hotspots = "\n".join(hot) or "- (no call edges extracted for this language)"

    area_block = ""
    if areas:
        rows = "\n".join(
            f"| {f'[`{a.name}`]({AREAS_SUBDIR}/{apages[a.name]}.md)' if a.name in apages else f'`{a.name}`'} "
            f"| {a.zone} | {len(a.modules)} | {a.types} | {a.functions} |"
            for a in areas
        )
        area_block = (
            "## Areas\nThe coarse components — start here, then drill into a module. "
            "An area is a module's first two path or namespace segments.\n\n"
            "| Area | Zone | Modules | Types | Functions |\n|---|---|---|---|---|\n"
            f"{rows}\n\n"
        )

    body = (
        f"**Graph size:** {stats.total_nodes} nodes · {stats.total_edges} edges\n\n"
        f"{area_block}"
        f"## Node kinds\n{counts}\n\n"
        f"## Module map (top 25 by members)\nThe biggest first-party modules — where the code lives. "
        f"Tests are excluded; each opens its page (or its source, if it has no page).\n\n{module_lines}\n\n"
        f"## Call hotspots (most-called functions)\nThe most-depended-on functions: what breaks the most "
        f"if you change it. Each links to its definition and to its direct callers; **reaches** is the "
        f"transitive blast radius — every symbol a change here can touch.\n\n{hotspots}"
    )
    return _doc("Architecture", body)


def render_domain_model(
    store: FactStore, *, src: str | None = None, entity_pages: dict[str, str] | None = None
) -> str:
    """The data model: every table, its foreign keys **both ways**, linked to its page.

    Foreign keys are rendered from both ends. Listing only ``references_of`` answers "what
    does this table point at" and leaves the more important question — "who depends on this
    table, so what breaks if I change it" — unanswerable from the page.
    """
    pages = entity_pages or {}
    entities = [n for n in store.nodes if n.kind is NodeKind.ENTITY]
    if not entities:
        # No DB/ORM entities; surface prominent source types (tests excluded).
        types = [n for n in store.nodes if n.kind is NodeKind.TYPE and not n.external and not _under_tests(n)]
        if not types:
            return _doc("Domain model", "_No data entities or domain types extracted yet._")
        listed = "\n".join(f"- {_link(t, src)}" for t in sorted(types, key=lambda n: (n.name, n.id))[:40])
        body = "_No DB/ORM entities detected._ Prominent domain types:\n\n" + listed
        return _doc("Domain model", body)

    def _cell(nodes: list[Node]) -> str:
        if not nodes:
            return "—"
        return ", ".join(
            f"[`{n.name}`]({ENTITIES_SUBDIR}/{pages[n.id]}.md)" if n.id in pages else f"`{n.name}`"
            for n in sorted(nodes, key=lambda n: (n.name, n.id))
        )

    rows: list[str] = []
    for ent in sorted(entities, key=lambda n: (n.name, n.id)):
        fields = [c for c in store.children_of(ent.id) if c.kind is NodeKind.FIELD]
        name = f"[`{ent.name}`]({ENTITIES_SUBDIR}/{pages[ent.id]}.md)" if ent.id in pages else _link(ent, src)
        rows.append(
            f"| {name} | {len(fields)} | {_cell(store.references_of(ent.id))} "
            f"| {_cell(store.dependents_of(ent.id))} |"
        )

    body = (
        f"{len(entities)} table{'s' if len(entities) != 1 else ''}. **Referenced by** is the "
        "half that matters when you're about to change one — those are the tables that "
        "depend on it.\n\n"
        "| Table | Fields | References | Referenced by |\n|---|---|---|---|\n" + "\n".join(rows)
    )
    return _doc("Domain model", body)


def render_conventions(root: Path) -> str:
    from orchestrator.sdlc.conventions import extract_conventions

    conv = extract_conventions(root)
    lint = [
        name
        for name in ("ruff.toml", ".ruff.toml", ".eslintrc", ".eslintrc.json", ".prettierrc")
        if (root / name).is_file()
    ]
    if (root / "pyproject.toml").is_file():
        try:
            if "[tool.ruff" in (root / "pyproject.toml").read_text(encoding="utf-8"):
                lint.append("pyproject [tool.ruff]")
        except OSError:
            pass
    parts: list[str] = []
    block = conv.prompt_block()
    if block:
        # The digest is phrased as codegen instructions; keep the observed rules.
        parts.append(block.split("\n", 1)[1] if "\n" in block else block)
    else:
        parts.append("_No conventions sampled yet._")
    if lint:
        parts.append("\n**Lint/format configs:** " + ", ".join(f"`{c}`" for c in lint))
    if conv.top_package:
        parts.append(f"\n**Top-level package:** `{conv.top_package}`")
    return _doc("Conventions", "\n".join(parts))


def render_glossary(store: FactStore) -> str:
    terms = sorted(
        {
            n.name
            for n in store.nodes
            if n.kind in (NodeKind.ENTITY, NodeKind.TYPE) and not n.external and not _under_tests(n)
        }
    )[:60]
    if not terms:
        return _doc("Glossary", "_No domain terms extracted yet._")
    body = "Starter glossary from prominent types/entities (define as the project matures):\n\n"
    body += "\n".join(f"- **{t}** — _TODO: definition_" for t in terms)
    return _doc("Glossary", body)


def render_progress_pointer() -> str:
    body = (
        "Feature progress is tracked in **`BACKLOG.md`** (written by `sdlc feature` / "
        "`orchestrator backlog`): `[ ]` todo, `[~]` in progress, `[x]` done (PR merged)."
    )
    return _doc("Progress", body)


def render_index(
    root: Path,
    *,
    greenfield: bool,
    summary: dict[str, int],
    module_pages: int = 0,
    area_pages: int = 0,
    entity_pages: int = 0,
) -> str:
    kind = "greenfield" if greenfield else "brownfield"
    pages_line = (
        f"- [`{AREAS_SUBDIR}/`]({AREAS_SUBDIR}/) — {area_pages} area pages: what each component is, "
        "what it depends on, and a map of its neighbours\n"
        if area_pages
        else ""
    )
    pages_line += (
        f"- [`{MODULES_SUBDIR}/`]({MODULES_SUBDIR}/) — {module_pages} module pages: every symbol, "
        "who calls it, and what it calls\n"
        if module_pages
        else ""
    )
    pages_line += (
        f"- [`{ENTITIES_SUBDIR}/`]({ENTITIES_SUBDIR}/) — {entity_pages} table pages: columns, "
        "foreign keys both ways, and the code that reads or writes it\n"
        if entity_pages
        else ""
    )
    body = (
        f"Code-true knowledge base for **{root.name}** ({kind}), built by "
        "`orchestrator understand` from the Product Knowledge Graph + project profile.\n\n"
        f"**Graph:** {summary.get('grounded_nodes', 0)} grounded nodes · {summary.get('edges', 0)} edges.\n\n"
        "> **epistēmē** (ἐπιστήμη) — knowledge grounded in evidence, as opposed to *doxa*, "
        "opinion. Everything here is derived from the code itself, not written by hand.\n\n"
        "## Files\n"
        "- [architecture.md](architecture.md) — module map, node kinds, call hotspots\n"
        f"{pages_line}"
        "- [domain-model.md](domain-model.md) — tables, fields, foreign keys both ways\n"
        "- [tech-context.md](tech-context.md) — languages, framework, db, tests\n"
        "- [conventions.md](conventions.md) — observed house style + lint config\n"
        "- [glossary.md](glossary.md) — domain terms\n"
        "- [progress.md](progress.md) → `BACKLOG.md`\n\n"
        "**Start at [architecture.md](architecture.md)** and click down: area → module → "
        "symbol → its source. Every relationship is rendered from both ends, so you can "
        "always walk back.\n\n"
        "_Regenerate with `orchestrator understand .` — structural files are rendered from "
        "code, so edits are advisory._"
    )
    return _doc("Episteme", body)


__all__ = [
    "MAX_MODULE_PAGES",
    "MODULES_SUBDIR",
    "module_page_slugs",
    "render_architecture",
    "render_module_page",
    "select_module_pages",
    "render_conventions",
    "render_domain_model",
    "render_glossary",
    "render_index",
    "render_progress_pointer",
    "render_tech_context",
]
