"""Deterministic memory-bank renderers: PKG facts + profile → markdown.

Pure functions, no LLM. Each returns a markdown document (or an empty-state note
for a greenfield repo). The PKG is the canonical source; these are the legible,
committed view.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from orchestrator.catalog.profile import ProjectProfile
from orchestrator.pkg.facts import EdgeKind, NodeKind
from orchestrator.pkg.stats import GraphStats
from orchestrator.pkg.store import FactStore

_HEADER = (
    "<!-- generated by `orchestrator understand`; the PKG is source of truth, edits here are advisory -->"
)

_GREENFIELD_NOTE = (
    "> **Greenfield** — little or no source yet. This will fill in as features land "
    "(re-run `orchestrator understand` or it refreshes each `sdlc feature` run)."
)


def _doc(title: str, body: str) -> str:
    return f"# {title}\n{_HEADER}\n\n{body.rstrip()}\n"


def _is_test_module(name: str) -> bool:
    return (
        name == "tests"
        or name.startswith(("tests.", "test_"))
        or ".tests." in name
        or name.endswith(".conftest")
    )


def _under_tests(node: object) -> bool:
    prov = getattr(node, "provenance", None)
    f = getattr(prov, "file", "") if prov else ""
    return f.startswith(("tests/", "test/")) or "/tests/" in f or "/test/" in f


def render_tech_context(profile: ProjectProfile, *, greenfield: bool) -> str:
    langs = ", ".join(sorted(profile.languages)) or "—"
    rows = [
        ("Languages", langs),
        ("Framework", profile.framework or "—"),
        ("Database", "yes" if profile.has_db else "no"),
        ("Migrations", "yes" if profile.has_migrations else "no"),
        ("Test runner", profile.test_runner or "—"),
        ("Task type (default)", profile.task_type),
    ]
    table = "| Aspect | Value |\n|---|---|\n" + "\n".join(f"| {k} | {v} |" for k, v in rows)
    body = (_GREENFIELD_NOTE + "\n\n" if greenfield else "") + table
    return _doc("Tech context", body)


def render_architecture(store: FactStore, stats: GraphStats, *, greenfield: bool) -> str:
    if greenfield or stats.total_nodes == 0:
        return _doc("Architecture", _GREENFIELD_NOTE)

    counts = "\n".join(
        f"- {kind.value}: {n}" for kind, n in sorted(stats.node_counts.items(), key=lambda kv: -kv[1]) if n
    )

    # Module map: first-party SOURCE modules (tests excluded) and their members (top 25).
    by_module: dict[str, dict[str, int]] = defaultdict(lambda: {"Type": 0, "Function": 0})
    modules = {
        n.id: n
        for n in store.nodes
        if n.kind is NodeKind.MODULE and not n.external and not _is_test_module(n.name)
    }
    for mod_id, mod in modules.items():
        for child in store.children_of(mod_id):
            if child.kind is NodeKind.TYPE:
                by_module[mod.name]["Type"] += 1
            elif child.kind is NodeKind.FUNCTION:
                by_module[mod.name]["Function"] += 1
    ranked = sorted(by_module.items(), key=lambda kv: -(kv[1]["Type"] + kv[1]["Function"]))[:25]
    module_lines = (
        "\n".join(
            f"- `{name}` — {c['Type']} types, {c['Function']} functions"
            for name, c in ranked
            if c["Type"] or c["Function"]
        )
        or "- (no first-party modules with members)"
    )

    hotspots = (
        "\n".join(f"- `{f.name}` — {f.call_count} call-sites" for f in stats.top_called_functions[:10])
        or "- (no call edges extracted for this language)"
    )

    body = (
        f"**Graph size:** {stats.total_nodes} nodes · {stats.total_edges} edges\n\n"
        f"## Node kinds\n{counts}\n\n"
        f"## Module map (top 25 by members)\n{module_lines}\n\n"
        f"## Call hotspots (most-called functions)\n{hotspots}"
    )
    return _doc("Architecture", body)


def render_domain_model(store: FactStore) -> str:
    entities = [n for n in store.nodes if n.kind is NodeKind.ENTITY]
    if not entities:
        # No DB/ORM entities; surface prominent source types (tests excluded).
        types = [n for n in store.nodes if n.kind is NodeKind.TYPE and not n.external and not _under_tests(n)]
        if not types:
            return _doc("Domain model", "_No data entities or domain types extracted yet._")
        listed = "\n".join(f"- `{t.name}`" for t in sorted(types, key=lambda n: n.name)[:40])
        body = "_No DB/ORM entities detected._ Prominent domain types:\n\n" + listed
        return _doc("Domain model", body)

    lines: list[str] = []
    for ent in sorted(entities, key=lambda n: n.name):
        fields = [c.name for c in store.children_of(ent.id) if c.kind is NodeKind.FIELD]
        refs = [r.name for r in store.references_of(ent.id)]
        lines.append(f"### `{ent.name}`")
        if fields:
            lines.append("Fields: " + ", ".join(f"`{f}`" for f in fields))
        if refs:
            lines.append(
                "References: " + ", ".join(f"`{r}`" for r in refs) + f"  *(via {EdgeKind.REFERENCES.value})*"
            )
        lines.append("")
    return _doc("Domain model", "\n".join(lines))


def render_conventions(root: Path) -> str:
    from orchestrator.sdlc.conventions import extract_conventions

    conv = extract_conventions(root)
    lint = [
        name
        for name in ("ruff.toml", ".ruff.toml", ".eslintrc", ".eslintrc.json", ".prettierrc")
        if (root / name).is_file()
    ]
    if (root / "pyproject.toml").is_file():
        try:
            if "[tool.ruff" in (root / "pyproject.toml").read_text(encoding="utf-8"):
                lint.append("pyproject [tool.ruff]")
        except OSError:
            pass
    parts: list[str] = []
    block = conv.prompt_block()
    if block:
        # The digest is phrased as codegen instructions; keep the observed rules.
        parts.append(block.split("\n", 1)[1] if "\n" in block else block)
    else:
        parts.append("_No conventions sampled yet._")
    if lint:
        parts.append("\n**Lint/format configs:** " + ", ".join(f"`{c}`" for c in lint))
    if conv.top_package:
        parts.append(f"\n**Top-level package:** `{conv.top_package}`")
    return _doc("Conventions", "\n".join(parts))


def render_glossary(store: FactStore) -> str:
    terms = sorted(
        {
            n.name
            for n in store.nodes
            if n.kind in (NodeKind.ENTITY, NodeKind.TYPE) and not n.external and not _under_tests(n)
        }
    )[:60]
    if not terms:
        return _doc("Glossary", "_No domain terms extracted yet._")
    body = "Starter glossary from prominent types/entities (define as the project matures):\n\n"
    body += "\n".join(f"- **{t}** — _TODO: definition_" for t in terms)
    return _doc("Glossary", body)


def render_progress_pointer() -> str:
    body = (
        "Feature progress is tracked in **`BACKLOG.md`** (written by `sdlc feature` / "
        "`orchestrator backlog`): `[ ]` todo, `[~]` in progress, `[x]` done (PR merged)."
    )
    return _doc("Progress", body)


def render_index(root: Path, *, greenfield: bool, summary: dict[str, int]) -> str:
    kind = "greenfield" if greenfield else "brownfield"
    body = (
        f"Code-true knowledge base for **{root.name}** ({kind}), built by "
        "`orchestrator understand` from the Product Knowledge Graph + project profile.\n\n"
        f"**Graph:** {summary.get('grounded_nodes', 0)} grounded nodes · {summary.get('edges', 0)} edges.\n\n"
        "## Files\n"
        "- [architecture.md](architecture.md) — module map, node kinds, call hotspots\n"
        "- [domain-model.md](domain-model.md) — entities, fields, references\n"
        "- [tech-context.md](tech-context.md) — languages, framework, db, tests\n"
        "- [conventions.md](conventions.md) — observed house style + lint config\n"
        "- [glossary.md](glossary.md) — domain terms\n"
        "- [progress.md](progress.md) → `BACKLOG.md`\n\n"
        "_Regenerate with `orchestrator understand .` — structural files are rendered from "
        "code, so edits are advisory._"
    )
    return _doc("Memory bank", body)


__all__ = [
    "render_architecture",
    "render_conventions",
    "render_domain_model",
    "render_glossary",
    "render_index",
    "render_progress_pointer",
    "render_tech_context",
]
