"""Deterministic knowledge-base renderers: PKG facts + profile → markdown.

Pure functions, no LLM. Each returns a markdown document (or an empty-state note
for a greenfield repo). The PKG is the canonical source; these are the legible,
committed view.

Every symbol named here deep-links to its definition (``provenance`` → a relative
``file#Lline`` link) so a reader can click through instead of leaving to grep, and
relationships render from *both* ends — a hotspot lists its callers, each of which
is itself a link. Output must stay **diff-stable**: these files are committed, so
a regeneration with no code change has to produce a zero-line diff. That means
every list is totally sorted; never rely on graph/edge iteration order.
"""

from __future__ import annotations

import hashlib
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import TYPE_CHECKING
from urllib.parse import quote

from orchestrator.catalog.profile import ProjectProfile
from orchestrator.knowledge.areas import AreaIndex, area_of_name, zone_of
from orchestrator.pkg.facts import EdgeKind, Node, NodeKind
from orchestrator.pkg.stats import GraphStats
from orchestrator.pkg.store import FactStore

if TYPE_CHECKING:
    from orchestrator.knowledge.current_state import CurrentState
    from orchestrator.knowledge.insights import OnboardingStep
    from orchestrator.sdlc.coverage import CoverageIndex

# How many callers to list under a hotspot on architecture.md before eliding. That page
# is orientation; the module page below is where the fuller list lives.
_MAX_CALLERS = 5

# The module page is the detail view, so it lists far more before eliding — "+N more" is
# itself a dead end, and this page exists precisely to be the end of that walk.
_MAX_CALLERS_PAGE = 25
# Symbols named in a module's "changing this safely" briefing. It's a briefing, not an
# inventory — past a handful the reader stops reading and the signal is gone.
_MAX_SAFETY_SYMBOLS = 8
_MAX_DOCS_PER_SYMBOL = 6

# The "what is this codebase built around" and glossary lists. Both were unranked A–Z
# dumps; ranked, a much shorter list carries more signal than a long one.
_MAX_CORE_TYPES = 25
_MAX_GLOSSARY_TERMS = 40

# Phase 5 surfaces. Each is a finding, not an inventory — the cap is what keeps it one.
_MAX_PUBLIC_SYMBOLS = 15
_MAX_CYCLES = 8
_MAX_CYCLE_MEMBERS = 6
# Languages where mutual inclusion is normal-ish (include guards make it compile).
_C_FAMILY = frozenset({"c", "cpp"})
_MAX_ONBOARDING_STEPS = 5
# The symbol index is the exception: it exists to be searched, so it wants to be long.
# Still capped, because a 10k-row table helps nobody and the cut has to be reported.
_MAX_INDEX_SYMBOLS = 1500

# How many modules get their own page. A page each is not survivable at real scale
# (this repo: 530 first-party modules; open5gs: 8.6k files) — the tail is listed on
# architecture.md instead, and the cut is always reported (principle 5).
MAX_MODULE_PAGES = 50

# Symbols listed on one module page before eliding. Generous: listing a module's
# symbols is the page's whole job, and most modules are far under this.
_MAX_SYMBOLS_PER_PAGE = 100

MODULES_SUBDIR = "modules"
AREAS_SUBDIR = "areas"
ENTITIES_SUBDIR = "entities"

# Entity pages. A schema with hundreds of tables is real; cap and report like the rest.
MAX_ENTITY_PAGES = 50

# Hotspots shown, and how deep to look for them. Each shown hotspot costs an `impact_of`
# BFS over callers — the one genuinely expensive render (~0.8s for 10 on a 981-module
# repo), which is why it is bounded here and not offered per-symbol on every module page.
# The candidate pool is much deeper than the display count because most top-ranked symbols
# are third-party and get filtered out.
_BLAST_RADIUS_HOTSPOTS = 10
HOTSPOT_CANDIDATES = 200

# Areas get pages too. Far fewer than modules by construction (an area is a coarse
# component), but a huge repo can still sprawl — cap and report.
MAX_AREA_PAGES = 25

# Neighbours drawn on an area's scoped diagram. The whole trick of a per-page diagram is
# that it is SCOPED: the repo-wide map needs a hard cap to stay readable, this doesn't.
_MAX_DIAGRAM_NEIGHBOURS = 8

_HEADER = (
    "<!-- generated by `orchestrator understand`; the PKG is source of truth, edits here are advisory -->"
)

# The provenance stamp: which commit this knowledge base was generated from, and by
# which Spine. Fenced by explicit markers because ``understand --check`` must ignore
# it — committing the episteme *itself* moves HEAD, so a freshly-generated bank is one
# commit "behind" the moment it lands. The content around it is what proves currency;
# the stamp is what tells a human reader roughly where they are. Deliberately carries
# **no timestamp** (invariant #2: same code in → same output out).
STAMP_OPEN = "<!-- spine-stamp -->"
STAMP_CLOSE = "<!-- /spine-stamp -->"

_GREENFIELD_NOTE = (
    "> **Greenfield** — little or no source yet. This will fill in as features land "
    "(re-run `orchestrator understand` or it refreshes each `sdlc feature` run)."
)


def _doc(title: str, body: str) -> str:
    return f"# {title}\n{_HEADER}\n\n{body.rstrip()}\n"


def render_stamp(*, commit: str | None, dirty: bool, version: str) -> str:
    """The fenced provenance block for the index page.

    States what is actually true — *generated from* commit X, not *describes HEAD* —
    because whether it still matches the code is exactly what ``--check`` answers, and
    a stamp can't answer it for itself. Outside git there is no commit to cite, so it
    says so rather than implying a currency it can't support (invariant #7).
    """
    if commit is None:
        line = (
            f"Generated by **Spine {version}** from a directory that isn't a git "
            "repository — there's no commit to tie this to."
        )
    else:
        smudge = " **plus uncommitted changes**" if dirty else ""
        line = f"Generated from commit `{commit}`{smudge} by **Spine {version}**."
    return (
        f"{STAMP_OPEN}\n{line}\n"
        "Verify it still matches the code with `orchestrator understand --check`.\n"
        f"{STAMP_CLOSE}"
    )


def strip_stamp(text: str) -> str:
    """Drop the fenced stamp block — what ``--check`` compares *around*.

    Applied to both sides of a comparison, so a bank whose stamp names an older
    commit still compares equal when its content is current.
    """
    if STAMP_OPEN not in text:
        return text
    out: list[str] = []
    skipping = False
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped == STAMP_OPEN:
            skipping = True
            continue
        if stripped == STAMP_CLOSE:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return "".join(out)


def _is_test_module(name: str) -> bool:
    return (
        name == "tests"
        or name.startswith(("tests.", "test_"))
        or ".tests." in name
        or name.endswith(".conftest")
    )


def _under_tests(node: object) -> bool:
    prov = getattr(node, "provenance", None)
    f = getattr(prov, "file", "") if prov else ""
    return f.startswith(("tests/", "test/")) or "/tests/" in f or "/test/" in f


def _link(node: Node, src: str | None, *, label: str | None = None) -> str:
    """A node as a source deep-link, degrading to plain text when it can't be one.

    ``src`` is the relative path from this document back to the repo root, or
    ``None`` when the bank lives outside the repo — in which case a link would be
    broken or machine-specific, so we render the location as text instead. An
    external node (no provenance) has no definition to point at.
    """
    text = label or node.name
    prov = node.provenance
    if prov is None:
        return f"`{text}`"
    if src is None:
        # Parenthetical, not a dash: these render mid-sentence ("- X — 2 types"),
        # and a second em-dash there is unreadable.
        return f"`{text}` (`{prov.file}:{prov.line}`)"
    return f"[`{text}`]({src}{quote(prov.file)}#L{prov.line})"


def _caller_line(store: FactStore, node_id: str, src: str | None) -> str:
    """The 'called by' backlink line for a hotspot — the other half of the edge.

    Sorted by (name, id): ``callers_of`` returns edge order, which is extraction
    order, which would churn the diff on every unrelated code change.
    """
    seen: dict[str, Node] = {cs.caller.id: cs.caller for cs in store.callers_of(node_id)}
    # Production callers first: they're the ones that tell you what the symbol is *for*.
    # A list that opens with five test functions has spent its budget saying "it's tested".
    callers = sorted(seen.values(), key=lambda n: (_under_tests(n), n.name, n.id))
    if not callers:
        return ""
    shown = ", ".join(_link(c, src) for c in callers[:_MAX_CALLERS])
    rest = len(callers) - _MAX_CALLERS
    more = f", +{rest} more" if rest > 0 else ""
    return f"\n  - called by {shown}{more}"


class Importance:
    """How central each symbol is to the codebase, indexed once.

    Several pages need to answer "which of these matter most" — the domain model, the
    glossary — and the honest answer is a graph question, not an alphabetical one. A
    page that sorts A–Z and calls the result *prominent* is claiming something it never
    computed; ``Abort`` led click's domain model because it starts with A.

    Production and test call-sites are counted **separately**, because a symbol called
    by thirty tests and nothing else is not central to the design — it's well tested.
    Both numbers are worth showing (Finding 6); only the production one drives ranking.

    One pass over the edges, so this is cheap even on a large graph — the per-node
    accessors each rescan every edge.
    """

    def __init__(self, store: FactStore) -> None:
        self.prod_callers: dict[str, int] = defaultdict(int)
        self.test_callers: dict[str, int] = defaultdict(int)
        self.implementors: dict[str, int] = defaultdict(int)
        self.mentions: dict[str, int] = defaultdict(int)
        self.members: dict[str, int] = defaultdict(int)
        for e in store.edges_of_kind(EdgeKind.CALLS):
            caller = store.node(e.src)
            if caller is not None and _under_tests(caller):
                self.test_callers[e.dst] += 1
            else:
                self.prod_callers[e.dst] += 1
        for e in store.edges_of_kind(EdgeKind.IMPLEMENTS):
            self.implementors[e.dst] += 1
        for e in store.edges_of_kind(EdgeKind.MENTIONS):
            self.mentions[e.dst] += 1
        for e in store.edges_of_kind(EdgeKind.CONTAINS):
            self.members[e.src] += 1

    def score(self, node_id: str) -> int:
        """A blunt, explainable weighting — subtypes and production callers count most.

        Test call-sites are worth **nothing** here, by design (Finding 6): being called
        by thirty tests makes a symbol well covered, not central, and letting that drive
        the ranking is precisely how test helpers crowd out the code someone came to
        read. The count is still displayed — it just doesn't get a vote.

        Deliberately not tuned beyond that: the point is to beat alphabetical order with
        something defensible, not to claim a precision the graph can't support.
        """
        return (
            3 * self.implementors[node_id]
            + 2 * self.prod_callers[node_id]
            + 2 * self.mentions[node_id]
            + self.members[node_id]
        )

    def rank(self, nodes: list[Node]) -> list[Node]:
        """Most central first; ties broken by name so the committed page diffs clean."""
        return sorted(nodes, key=lambda n: (-self.score(n.id), n.name, n.id))

    def caller_split(self, node_id: str) -> str:
        """ "12 production · 30 test call-sites" — better than either number alone."""
        prod, test = self.prod_callers[node_id], self.test_callers[node_id]
        if not prod and not test:
            return ""
        if prod and test:
            return f"{prod} production · {test} test call-sites"
        n, label = (prod, "production") if prod else (test, "test")
        return f"{n} {label} call-site{'s' if n != 1 else ''}"


def _slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.")
    return s[:80] or "module"


def module_page_slugs(names: list[str]) -> dict[str, str]:
    """Module name → unique page stem.

    Names become filenames and they are wild across the front-ends: dotted namespaces
    (``App.Api``), paths (``src/smf/smf-sm.c``), symbols (``cpp:A::A``). Collisions are
    resolved with a short digest of the full name, and checked **case-folded** — macOS
    and Windows filesystems are case-insensitive, so ``Foo.md`` and ``foo.md`` would
    silently clobber each other. Assignment walks sorted names, so the mapping is
    identical run to run (principle 4).
    """
    out: dict[str, str] = {}
    used: set[str] = set()
    for name in sorted(names):
        stem = _slug(name)
        if stem.lower() in used:
            stem = f"{stem}-{hashlib.sha1(name.encode(), usedforsecurity=False).hexdigest()[:6]}"
        used.add(stem.lower())
        out[name] = stem
    return out


def select_module_pages(store: FactStore, *, limit: int = MAX_MODULE_PAGES) -> list[Node]:
    """The first-party modules worth a page, biggest first (ties broken by name).

    Capped: a page per module is not survivable at real scale, and an unbounded
    page set would bury the reader as surely as no pages at all.
    """
    mods = [
        n for n in store.nodes if n.kind is NodeKind.MODULE and not n.external and not _is_test_module(n.name)
    ]
    sized: list[tuple[Node, int]] = []
    for m in mods:
        members = sum(1 for c in store.children_of(m.id) if c.kind in (NodeKind.TYPE, NodeKind.FUNCTION))
        if members:
            sized.append((m, members))
    sized.sort(key=lambda t: (-t[1], t[0].name))
    return [m for m, _ in sized[:limit]]


class ModuleDeps:
    """The module-level import graph, resolved once.

    **IMPORTS edges target the imported *symbol*, not the module** — the Python
    front-end emits ``py:web.views -> py:app.core.slugify``. So a module's importers are
    *always empty* if you ask ``importers_of(module_id)``: nothing ever points at a module
    id. Both endpoints have to be walked up to their owning module (the CONTAINS walk in
    ``AreaIndex``) before there is a module→module edge to render at all.
    """

    def __init__(self, store: FactStore, index: AreaIndex) -> None:
        self.imports: dict[str, set[str]] = defaultdict(set)
        self.importers: dict[str, set[str]] = defaultdict(set)
        for edge in store.edges_of_kind(EdgeKind.IMPORTS):
            src_node, dst_node = store.node(edge.src), store.node(edge.dst)
            if src_node is None or dst_node is None:
                continue
            src_mod, dst_mod = index.module_of(src_node), index.module_of(dst_node)
            if src_mod is None or dst_mod is None or src_mod.id == dst_mod.id:
                continue
            self.imports[src_mod.id].add(dst_mod.id)
            self.importers[dst_mod.id].add(src_mod.id)


def _symbol_section(store: FactStore, sym: Node, src: str | None) -> list[str]:
    """One symbol as an anchorable subsection: definition, who calls it, what it calls.

    The heading is what makes ``modules/foo.md#normalize`` addressable — symbols get
    anchors, not files (a file per symbol does not survive a 10k-node graph).
    """
    out = [f"### `{sym.name}`", ""]
    prov = sym.provenance
    if prov is not None:
        loc = f"{prov.file}:{prov.line}"
        out.append(f"`{loc}`" if src is None else f"[`{loc}`]({src}{quote(prov.file)}#L{prov.line})")
        out.append("")

    # Inheritance first, and from both ends: "what is this a kind of" and "what are the
    # kinds of this" are the two halves of a hierarchy, and a page that answers only one
    # can't be walked back up. These edges existed all along with nothing rendering them.
    facts: list[str] = []
    for title, nodes in (
        ("Extends", store.implements_of(sym.id)),
        ("Implemented by", store.implementors_of(sym.id)),
        ("Called by", [c.caller for c in store.callers_of(sym.id)]),
        ("Calls", store.callees_of(sym.id)),
    ):
        uniq = sorted({n.id: n for n in nodes}.values(), key=lambda n: (n.name, n.id))
        if not uniq:
            continue
        if title == "Called by":
            # Production callers first, and counted apart: a symbol whose callers are all
            # tests is well covered, not central, and the two shouldn't read the same.
            uniq.sort(key=lambda n: (_under_tests(n), n.name, n.id))
            prod = sum(1 for n in uniq if not _under_tests(n))
            count = f"{prod} production · {len(uniq) - prod} test" if prod != len(uniq) else str(len(uniq))
        else:
            count = str(len(uniq))
        shown = ", ".join(_link(n, src) for n in uniq[:_MAX_CALLERS_PAGE])
        rest = len(uniq) - _MAX_CALLERS_PAGE
        facts.append(f"- **{title}** ({count}): {shown}" + (f", +{rest} more" if rest > 0 else ""))

    fields = sorted(c.name for c in store.children_of(sym.id) if c.kind is NodeKind.FIELD)
    if fields:
        facts.append("- **Fields**: " + ", ".join(f"`{f}`" for f in fields))

    docs = sorted({d.id: d for d in store.docs_for(sym.id)}.values(), key=lambda n: (n.name, n.id))
    if docs:
        facts.append("- **Documented in**: " + ", ".join(f"`{d.name}`" for d in docs[:_MAX_DOCS_PER_SYMBOL]))

    # A symbol with no edges at all would otherwise render as a heading, a location, and
    # silence — which reads like the page gave up rather than like a fact about the code.
    out += facts or ["_No relationships extracted — nothing in the graph calls it or extends it._"]
    out.append("")
    return out


def _safety_block(
    store: FactStore,
    module: Node,
    src: str | None,
    cov: CoverageIndex,
    deps: ModuleDeps,
) -> list[str]:
    """ "Changing this safely" — what a change here reaches, and where no test can be seen.

    This is the most persuasive thing the graph knows ("four functions in the blast
    radius of your change, and no test covers any of them"), and it used to be available
    only by running ``regression`` against a symbol you had already decided to change.
    Precomputing it per module puts it where someone is already looking, *before* they
    pick the symbol.

    **Bounded honestly, and the bound matters here.** Call resolution is precision-first:
    the Python front-end resolves bare names and ``self.method()`` but deliberately skips
    ambiguous attribute chains, so a test exercising a symbol through ``obj.method()``
    leaves no visible path. Reporting that as "no test covers this" would be a confident
    falsehood — it named ``click.Context``, one of the most tested classes in the
    ecosystem. So this flags only the *actionable intersection* Finding 9 describes —
    symbols that other code depends on **and** have no visible test path — and says
    plainly that invisible is not the same as absent. Module-level "tested by" uses test
    **imports** instead, which are complete in a way call edges are not.

    Silent when the language has no call graph: an empty radius would read as "nothing
    depends on this", a very different claim from "we can't see".
    """
    if not cov.call_graph_available:
        return []
    symbols = [c for c in store.children_of(module.id) if c.kind in (NodeKind.TYPE, NodeKind.FUNCTION)]
    if not symbols:
        return []

    ranked = sorted(
        ((s, cov.blast_radius(s.id)) for s in symbols),
        key=lambda pair: (-len(pair[1]), pair[0].name, pair[0].id),
    )
    reaching = [(s, radius) for s, radius in ranked if radius]
    # The intersection worth acting on: something depends on it, and no test path exists.
    at_risk = [(s, radius) for s, radius in reaching if not cov.is_covered(s.id)]

    testers = sorted(
        (n for i in deps.importers.get(module.id, set()) if (n := store.node(i)) and _is_test_module(n.name)),
        key=lambda n: (n.name, n.id),
    )
    if not reaching and not testers:
        return []

    out = ["## Changing this safely", ""]
    if testers:
        listed = ", ".join(f"`{t.name}`" for t in testers[:_MAX_SAFETY_SYMBOLS])
        rest = len(testers) - _MAX_SAFETY_SYMBOLS
        out += [
            f"**Tested by** ({len(testers)}): {listed}" + (f", +{rest} more" if rest > 0 else ""),
            "",
        ]
    else:
        out += ["**No test module imports this.**", ""]

    if reaching:
        out += [
            "**Most depended-upon here** — a change to these reaches the most code (call graph, ≤4 hops):",
            "",
        ]
        out += [
            f"- {_link(s, src)} — reaches **{len(radius)}** symbol{'s' if len(radius) != 1 else ''}"
            + ("" if cov.is_covered(s.id) else " · **no test path visible**")
            for s, radius in reaching[:_MAX_SAFETY_SYMBOLS]
        ]
        out.append("")
    if at_risk:
        out += [
            f"_{len(at_risk)} of the symbols other code depends on here have no test path the "
            "graph can see — worth a second look before changing them. Absence of a path is "
            "not proof of absence of a test: calls through an attribute chain (`obj.method()`) "
            "are skipped rather than guessed at, so indirect coverage is invisible._",
            "",
        ]
    return out


def _module_dep_section(
    store: FactStore, module: Node, page_of: dict[str, str], src: str | None, deps: ModuleDeps
) -> list[str]:
    """Imports and imported-by — the dependency edge rendered from both ends.

    Reads the resolved module→module graph, not raw IMPORTS edges: those point at the
    imported symbol, so asking the edges directly renders "imports `slugify`" (a symbol,
    not a dependency) and an always-empty "Imported by".

    A sibling that has its own page links to it; one that doesn't degrades to its name.
    Never link to a page we didn't write.
    """
    out: list[str] = []
    for title, ids in (
        ("Imports", deps.imports.get(module.id, set())),
        ("Imported by", deps.importers.get(module.id, set())),
    ):
        nodes = [n for n in (store.node(i) for i in ids) if n is not None]
        uniq = sorted(nodes, key=lambda n: (n.name, n.id))
        if not uniq:
            continue
        rendered = [f"[`{n.name}`]({page_of[n.id]}.md)" if n.id in page_of else _link(n, src) for n in uniq]
        out += [f"## {title}", "", ", ".join(rendered), ""]
    return out


def render_module_page(
    store: FactStore,
    module: Node,
    *,
    src: str | None,
    page_of: dict[str, str],
    deps: ModuleDeps,
    cov: CoverageIndex | None = None,
) -> str:
    """One module's page: what the code is, what breaks, and what isn't tested.

    ``src`` is the path from ``episteme/modules/`` back to the repo root (one level
    deeper than the top-level docs); ``page_of`` maps module id → page stem for the
    modules that actually got one; ``deps`` is the resolved module→module import graph.
    ``cov`` adds the "changing this safely" briefing; without it the page is the symbol
    reference it has always been.
    """
    children = store.children_of(module.id)
    types = sorted((c for c in children if c.kind is NodeKind.TYPE), key=lambda n: (n.name, n.id))
    funcs = sorted((c for c in children if c.kind is NodeKind.FUNCTION), key=lambda n: (n.name, n.id))

    head = ["[← Episteme](../README.md) · [Architecture](../architecture.md)", ""]
    prov = module.provenance
    if prov is not None:
        loc = prov.file
        head.append(f"**Source:** `{loc}`" if src is None else f"**Source:** [`{loc}`]({src}{quote(loc)})")
    # One line, assembled before appending — these are joined with "\n", so appending
    # the language separately would drop it onto a line of its own.
    counts = f"{len(types)} types · {len(funcs)} functions"
    if module.language:
        counts += f" · {module.language}"
    head += ["", counts, ""]

    body = list(head)
    # The briefing goes above the symbol reference: it's what you need before deciding
    # to touch anything, and the reference is what you read once you have.
    if cov is not None:
        body += _safety_block(store, module, src, cov, deps)
    docs = sorted({d.id: d for d in store.docs_for(module.id)}.values(), key=lambda n: (n.name, n.id))
    if docs:
        body += [
            "## Documented in",
            "",
            ", ".join(f"`{d.name}`" for d in docs[:_MAX_DOCS_PER_SYMBOL]),
            "",
        ]

    budget = _MAX_SYMBOLS_PER_PAGE
    for title, syms in (("Types", types), ("Functions", funcs)):
        if not syms:
            continue
        body += [f"## {title}", ""]
        for sym in syms[:budget]:
            body += _symbol_section(store, sym, src)
        elided = len(syms) - budget
        if elided > 0:
            body.append(f"_+{elided} more {title.lower()} not shown (see the graph)._\n")
        budget = max(0, budget - len(syms))

    body += _module_dep_section(store, module, page_of, src, deps)
    return _doc(f"`{module.name}`", "\n".join(body).rstrip())


class DataLayer:
    """Who reads and writes each entity, indexed once.

    ``store`` answers the FK questions (``references_of`` / ``dependents_of``) but has no
    query for READS/WRITES, so index them here — same shape as ``ModuleDeps``: aggregate
    the whole graph once rather than rescan every edge per entity.
    """

    def __init__(self, store: FactStore) -> None:
        self.readers: dict[str, set[str]] = defaultdict(set)
        self.writers: dict[str, set[str]] = defaultdict(set)
        for e in store.edges_of_kind(EdgeKind.READS):
            self.readers[e.dst].add(e.src)
        for e in store.edges_of_kind(EdgeKind.WRITES):
            self.writers[e.dst].add(e.src)


def _field_label(field: Node, entity: Node) -> str:
    """A field's own name. Field ids/names are table-qualified (``customers.id``), so
    rendering them raw under their own table repeats the table on every line."""
    prefix = f"{entity.name}."
    return field.name[len(prefix) :] if field.name.startswith(prefix) else field.name


def select_entity_pages(store: FactStore, *, limit: int = MAX_ENTITY_PAGES) -> list[Node]:
    """The entities worth a page — most-connected first, ties broken by name."""
    entities = [n for n in store.nodes if n.kind is NodeKind.ENTITY]
    ranked = sorted(
        entities,
        key=lambda e: (
            -(len(store.references_of(e.id)) + len(store.dependents_of(e.id))),
            e.name,
        ),
    )
    return ranked[:limit]


def render_entity_page(
    store: FactStore,
    entity: Node,
    *,
    src: str | None,
    entity_pages: dict[str, str],
    data: DataLayer,
) -> str:
    """One table: its columns, its foreign keys **both ways**, and the code that touches it.

    "Referenced by" is the half that was missing entirely: `references_of` answers what
    *this* table points at, and a reader looking at `customers` needs the opposite — which
    tables depend on it, i.e. what a change here can break.
    """
    fields = sorted(
        (c for c in store.children_of(entity.id) if c.kind is NodeKind.FIELD),
        key=lambda n: (n.name, n.id),
    )
    refs = sorted(store.references_of(entity.id), key=lambda n: (n.name, n.id))
    deps = sorted(store.dependents_of(entity.id), key=lambda n: (n.name, n.id))

    body = ["[← Episteme](../README.md) · [Domain model](../domain-model.md)", ""]
    prov = entity.provenance
    if prov is not None:
        loc = f"{prov.file}:{prov.line}"
        body.append(
            f"**Defined in:** `{loc}`"
            if src is None
            else f"**Defined in:** [`{loc}`]({src}{quote(prov.file)}#L{prov.line})"
        )
        body.append("")

    body.append(
        f"{len(fields)} field{'s' if len(fields) != 1 else ''} · "
        f"references {len(refs)} · referenced by {len(deps)}"
    )
    body.append("")

    if fields:
        body += ["## Fields", ""]
        body += [f"- `{_field_label(f, entity)}`" for f in fields]
        body.append("")

    def _ent_link(n: Node) -> str:
        return f"[`{n.name}`]({entity_pages[n.id]}.md)" if n.id in entity_pages else f"`{n.name}`"

    for title, nodes, note in (
        ("References", refs, "tables this one points at (foreign keys out)"),
        ("Referenced by", deps, "tables that depend on this one — a change here reaches them"),
    ):
        if not nodes:
            continue
        body += [f"## {title}", "", f"_{note}_", "", ", ".join(_ent_link(n) for n in nodes), ""]

    for title, ids in (
        ("Read by", data.readers.get(entity.id, set())),
        ("Written by", data.writers.get(entity.id, set())),
    ):
        nodes = [n for n in (store.node(i) for i in ids) if n is not None]
        if not nodes:
            continue
        rendered = [_link(n, src) for n in sorted(nodes, key=lambda n: (n.name, n.id))]
        body += [f"## {title}", "", ", ".join(rendered), ""]

    return _doc(f"`{entity.name}`", "\n".join(body).rstrip())


class AreaFacts:
    """One area's shape, collected once so the prose and the diagram agree."""

    def __init__(self, name: str, modules: list[Node]) -> None:
        self.name = name
        self.zone = zone_of(name)
        self.modules = sorted(modules, key=lambda n: (n.name, n.id))
        self.types = 0
        self.functions = 0
        self.imports: set[str] = set()  # areas this one depends on
        self.importers: set[str] = set()  # areas that depend on this one

    @property
    def size(self) -> int:
        return self.types + self.functions


def collect_areas(store: FactStore, deps: ModuleDeps) -> dict[str, AreaFacts]:
    """Group first-party modules into areas and lift the import graph to area→area.

    Self-edges are dropped: an area importing itself is noise, not architecture. Edges to
    modules outside the first-party set (third-party, tests) are dropped too — this is a
    map of *this* project's components.
    """
    areas: dict[str, AreaFacts] = {}
    area_of_module: dict[str, str] = {}
    for mod in store.nodes:
        if mod.kind is not NodeKind.MODULE or mod.external or _is_test_module(mod.name):
            continue
        name = area_of_name(mod.name)
        area_of_module[mod.id] = name
        areas.setdefault(name, AreaFacts(name, [])).modules.append(mod)

    for name, area in areas.items():
        area.modules.sort(key=lambda n: (n.name, n.id))
        for mod in area.modules:
            for child in store.children_of(mod.id):
                if child.kind is NodeKind.TYPE:
                    area.types += 1
                elif child.kind is NodeKind.FUNCTION:
                    area.functions += 1
            for dep_id in deps.imports.get(mod.id, set()):
                other = area_of_module.get(dep_id)
                if other and other != name:
                    area.imports.add(other)
            for dep_id in deps.importers.get(mod.id, set()):
                other = area_of_module.get(dep_id)
                if other and other != name:
                    area.importers.add(other)
    return areas


def select_area_pages(areas: dict[str, AreaFacts], *, limit: int = MAX_AREA_PAGES) -> list[AreaFacts]:
    """The areas worth a page, biggest first (ties broken by name)."""
    ranked = sorted((a for a in areas.values() if a.size), key=lambda a: (-a.size, a.name))
    return ranked[:limit]


def _area_prose(area: AreaFacts, total_areas: int) -> str:
    """The derived 'what this is' — templated from facts, no LLM, no network.

    This is the deterministic tier: it states what the graph knows (size, role, who
    depends on it) and never guesses at intent. Prose that *explains why* is a separate,
    opt-in tier — it must never become a hard dependency of this one, or regenerating the
    episteme would need an API key, and a knowledge base that can't be regenerated rots.
    """
    what = (
        f"**`{area.name}`** is one of {total_areas} areas in this repo, "
        f"in the `{area.zone}` zone. It holds {len(area.modules)} "
        f"module{'s' if len(area.modules) != 1 else ''} — {area.types} types and "
        f"{area.functions} functions."
    )
    if area.importers and area.imports:
        role = (
            f"It sits in the middle of the graph: {len(area.imports)} "
            f"area{'s' if len(area.imports) != 1 else ''} below it, "
            f"{len(area.importers)} above. Changes here can reach both ways."
        )
    elif area.importers:
        role = (
            f"Nothing here depends on other areas, but {len(area.importers)} "
            f"area{'s' if len(area.importers) != 1 else ''} depend{'s' if len(area.importers) == 1 else ''} "
            "on it — it's a foundation, so changes ripple outward."
        )
    elif area.imports:
        # State the structure; don't infer safety from it. "Nothing imports this" is
        # exactly what an application entry point looks like — on open5gs it fired for
        # `src/amf`, a 390-function network function, calling it "the safer place to
        # change". Being un-imported bounds what a change can reach *outward*; it says
        # nothing about how much lives inside.
        role = (
            f"No other area imports it, and it draws on {len(area.imports)} — nothing else "
            "in this repo depends on it. That's the shape of an entry point or a top-level "
            "application as much as a leaf utility, so it bounds the outward reach of a "
            "change here, not its difficulty."
        )
    else:
        role = "It has no import edges to or from other areas — it stands alone."
    return f"{what} {role}"


def _mermaid_id(name: str, i: int) -> str:
    """A mermaid-safe node id. Positional, so it can't collide and can't leak punctuation."""
    return f"n{i}"


def _area_diagram(area: AreaFacts, page_of: dict[str, str]) -> list[str]:
    """This area and its immediate neighbours, plus a linked legend.

    Scoped on purpose: the repo-wide map in `state` needs a hard 18-node cap to stay
    readable *because it draws everything*. Here we draw one area and its neighbours —
    small enough to read without a cap fighting us.

    **No `click` directives.** GitHub renders mermaid with securityLevel=strict and offers
    no way to loosen it, so `click` does nothing there — and can make GitHub refuse the
    diagram entirely ("This content is blocked"). The legend below the diagram does the
    navigating instead; it works everywhere markdown does.
    """
    ins = sorted(area.importers)[:_MAX_DIAGRAM_NEIGHBOURS]
    outs = sorted(area.imports)[:_MAX_DIAGRAM_NEIGHBOURS]
    if not ins and not outs:
        return []

    # An area can be both an importer and an import (a mutual dependency), so dedupe
    # before declaring nodes — otherwise it gets two node lines and two legend entries.
    # The two *edges* are kept: a cycle pointing both ways is a real fact worth seeing.
    neighbours: list[str] = []
    for other in ins + outs:
        if other not in neighbours:
            neighbours.append(other)
    ids = {name: _mermaid_id(name, i) for i, name in enumerate(neighbours, start=1)}

    def _label(name: str) -> str:
        # Quoted labels tolerate dots/slashes; a stray quote would break the parse.
        return name.replace('"', "'")

    out = ["```mermaid", "flowchart LR"]
    out.append(f'  n0["{_label(area.name)}"]')
    for other in neighbours:
        out.append(f'  {ids[other]}["{_label(other)}"]')
    for other in ins:
        out.append(f"  {ids[other]} --> n0")
    for other in outs:
        out.append(f"  n0 --> {ids[other]}")
    out += ["```", ""]

    legend = [f"**`{area.name}`** (this area)"]
    legend += [
        f"[`{other}`]({page_of[other]}.md)" if other in page_of else f"`{other}`" for other in neighbours
    ]
    out += ["**In the diagram:** " + " · ".join(legend), ""]
    if len(area.importers) > len(ins) or len(area.imports) > len(outs):
        shown, total = len(ins) + len(outs), len(area.importers) + len(area.imports)
        out += [f"_Showing {shown} of {total} neighbouring areas._", ""]
    return out


def render_area_page(
    area: AreaFacts,
    *,
    total_areas: int,
    src: str | None,
    area_pages: dict[str, str],
    module_pages: dict[str, str],
) -> str:
    """One area: what it is, the picture, its modules, and its neighbours both ways."""
    body = [
        "[← Episteme](../README.md) · [Architecture](../architecture.md)",
        "",
        _area_prose(area, total_areas),
        "",
    ]
    body += _area_diagram(area, area_pages)

    body += ["## Modules", ""]
    for mod in area.modules:
        if mod.id in module_pages:
            link = f"[`{mod.name}`](../{MODULES_SUBDIR}/{module_pages[mod.id]}.md)"
        else:
            link = _link(mod, src)
        body.append(f"- {link}")
    body.append("")

    for title, names in (("Depends on", sorted(area.imports)), ("Depended on by", sorted(area.importers))):
        if not names:
            continue
        rendered = [f"[`{n}`]({area_pages[n]}.md)" if n in area_pages else f"`{n}`" for n in names]
        body += [f"## {title}", "", ", ".join(rendered), ""]

    return _doc(f"`{area.name}`", "\n".join(body).rstrip())


def project_name(root: Path) -> str:
    """What this project calls itself, preferring its manifest over the directory name.

    The directory name is a property of *this checkout*, not of the project: a bank
    generated in ``~/dev/spine`` and checked in a CI workspace called
    ``agent-orachestrator`` would disagree about the repo's own name and report itself
    stale. A committed artifact has to be identical for everyone at a given commit, so
    it takes the declared name where there is one.
    """
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        try:
            import tomllib

            name = (tomllib.loads(pyproject.read_text(encoding="utf-8")).get("project") or {}).get("name")
            if name:
                return str(name)
        except (OSError, ValueError, ModuleNotFoundError):
            pass
    package_json = root / "package.json"
    if package_json.is_file():
        try:
            import json

            name = json.loads(package_json.read_text(encoding="utf-8")).get("name")
            if name:
                return str(name)
        except (OSError, ValueError):
            pass
    return root.name


def _declared_versions(root: Path | None) -> list[tuple[str, str]]:
    """Version and language floor as the project's own manifest declares them.

    Read, never inferred: a version this page states has to be the one the repo ships.
    """
    if root is None:
        return []
    rows: list[tuple[str, str]] = []
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        try:
            import tomllib

            project = tomllib.loads(pyproject.read_text(encoding="utf-8")).get("project", {}) or {}
            if project.get("version"):
                rows.append(("Version", f"`{project['version']}`"))
            if project.get("requires-python"):
                rows.append(("Requires Python", f"`{project['requires-python']}`"))
        except (OSError, ValueError, ModuleNotFoundError):
            pass
    package_json = root / "package.json"
    if not rows and package_json.is_file():
        try:
            import json

            data = json.loads(package_json.read_text(encoding="utf-8"))
            if data.get("version"):
                rows.append(("Version", f"`{data['version']}`"))
            engines = (data.get("engines") or {}).get("node")
            if engines:
                rows.append(("Requires Node", f"`{engines}`"))
        except (OSError, ValueError):
            pass
    return rows


def render_tech_context(
    profile: ProjectProfile,
    *,
    greenfield: bool,
    state: CurrentState | None = None,
    root: Path | None = None,
) -> str:
    """What this project is built on, what it needs to run, and how it starts.

    ``state`` (the shared analysis) supplies infrastructure, entry points, and the
    external dependencies `state` reports — without it the page is the six-row profile
    table it has always been.
    """
    langs = ", ".join(sorted(profile.languages)) or "—"
    rows = [
        ("Languages", langs),
        ("Framework", profile.framework or "—"),
        ("Database", "yes" if profile.has_db else "no"),
        ("Migrations", "yes" if profile.has_migrations else "no"),
        ("Test runner", profile.test_runner or "—"),
        ("Task type (default)", profile.task_type),
        *_declared_versions(root),
    ]
    table = "| Aspect | Value |\n|---|---|\n" + "\n".join(f"| {k} | {v} |" for k, v in rows)
    body = (_GREENFIELD_NOTE + "\n\n" if greenfield else "") + table
    if state is not None:
        body += _infrastructure_block(state) + _entry_points_block(state) + _external_deps_block(state)
    return _doc("Tech context", body)


def _infrastructure_block(state: CurrentState) -> str:
    """What the repo *declares* it needs, read from manifests and container configs."""
    inf = state.infrastructure
    if inf is None or inf.is_empty():
        return ""
    out = (
        "\n\n## Infrastructure & runtime\n"
        "_Read from manifests, build files, and container configs. Absence means "
        '"not declared here", not "unused"._\n\n'
    )
    if inf.summary:
        out += f"**To stand it up, you'll need:** {', '.join(inf.summary)}.\n\n"
    out += "\n".join(f"- **{cat}:** {', '.join(items)}" for cat, items in inf.categories.items())
    return out


def _entry_points_block(state: CurrentState) -> str:
    if not state.entry_points:
        return ""
    listed = "\n".join(f"- {e}" for e in state.entry_points[:8])
    return f"\n\n## Entry points\n_How this system starts._\n\n{listed}"


def _external_deps_block(state: CurrentState) -> str:
    """Imports that leave the codebase, ranked by how often they're reached for.

    This counts every out-of-repo import — third-party *and* standard library, test
    dependencies included. That's a wider net than a manifest's dependency list, so the
    heading says what it is rather than implying it's the install list.
    """
    if not state.external_deps:
        return ""
    top = state.external_deps.most_common(10)
    listed = "\n".join(f"- `{dep}` — imported {n} time{'s' if n != 1 else ''}" for dep, n in top)
    total = len(state.external_deps)
    tail = f"\n\n_Top {len(top)} of {total}._" if total > len(top) else ""
    return (
        "\n\n## Most-used external imports\n"
        "_Everything imported from outside this codebase, by how often — standard "
        "library and test dependencies included, so this is wider than the install list._"
        f"\n\n{listed}{tail}"
    )


def _system_architecture_block(state: CurrentState) -> str:
    """The component dependency picture — diagram + the strongest edges, in words.

    Drawn from ``current_state``'s own bounded ``architecture_graph``, so the committed
    page and the printed report can never show a different architecture for the same
    commit. Empty when the import graph has no cross-component edges to draw — no
    picture beats a wrong picture.
    """
    from orchestrator.knowledge.current_state import architecture_mermaid

    if not state.coupling:
        return ""
    rows = "\n".join(f"| `{a}` | → | `{b}` | {c} |" for (a, b), c in state.coupling.most_common(10))
    diagram = "\n".join(architecture_mermaid(state))
    return (
        "## System architecture\n"
        "The top components grouped by zone; arrows run in the direction of the "
        "dependency, weighted by how many imports back them.\n\n"
        f"{diagram}\n\n"
        "### Strongest component dependencies\n\n"
        f"| From | → | To | Strength |\n|---|---|---|---|\n{rows}\n\n"
    )


def _layers_block(state: CurrentState) -> str:
    if not state.layers:
        return ""
    rows = "\n".join(f"| {layer} | {n} |" for layer, n in state.layers.most_common())
    return (
        "## Layers\n"
        "Types bucketed by role, inferred from naming conventions — a rough shape of the "
        "codebase, not a declared architecture.\n\n"
        f"| Layer | Types |\n|---|---|\n{rows}\n\n"
    )


def _core_types_page(store: FactStore, src: str | None) -> str:
    """What this codebase is built around, when there's no database to describe.

    Most repos have no DB, and for them this page used to be an alphabetical listing of
    every class — 40+ entries where "prominent" was asserted and never computed. Ranked
    by graph centrality it becomes the page it was always meant to be: the handful of
    types you need to know to read the code. Retitled too, because on a repo with no
    database "domain model" promises a schema that isn't there.
    """
    types = [n for n in store.nodes if n.kind is NodeKind.TYPE and not n.external and not _under_tests(n)]
    if not types:
        return _doc("Domain model", "_No data entities or domain types extracted yet._")

    imp = Importance(store)
    ranked = imp.rank(types)[:_MAX_CORE_TYPES]
    rows: list[str] = []
    for t in ranked:
        subs = imp.implementors[t.id]
        detail = [
            f"{imp.members[t.id]} members" if imp.members[t.id] else "",
            f"{subs} subtype{'s' if subs != 1 else ''}" if subs else "",
            f"used by {imp.caller_split(t.id)}" if imp.caller_split(t.id) else "",
        ]
        rows.append(f"| {_link(t, src)} | {' · '.join(d for d in detail if d) or '—'} |")

    body = (
        "_No database or ORM entities detected, so this is the **code's** model: the types "
        "this codebase is built around, ranked by how much of the graph depends on them "
        "(subtypes, production call-sites, members, doc mentions)._\n\n"
        "| Type | Why it matters |\n|---|---|\n" + "\n".join(rows)
    )
    if len(types) > len(ranked):
        body += f"\n\n_Top {len(ranked)} of {len(types)} types; the rest are in the module pages._"
    return _doc("Domain model", body)


def _documentation_block(state: CurrentState) -> str:
    """How much of the code the repo's own docs describe, and where they've drifted.

    Four releases of doc ingestion reduced, in the committed bank, to a single
    ``Doc: 264`` line under node kinds. Coverage and drift are the parts a reader can
    act on. Empty when a repo has no ingested docs.
    """
    if not state.docs:
        return ""
    pct = round(100 * state.documented_symbols / state.coverable_symbols) if state.coverable_symbols else 0
    out = (
        "## Documentation\n"
        "_The repo's own prose folded into the graph (`Doc` nodes + `MENTIONS` edges). "
        "A mention counts only when it binds to exactly one symbol, so this under-counts "
        "rather than guesses._\n\n"
        f"**{state.docs} doc{'s' if state.docs != 1 else ''}** ingested, naming "
        f"**{state.documented_symbols} of {state.coverable_symbols} symbols** ({pct}% doc coverage).\n\n"
    )
    if state.doc_drift_total:
        rows = "\n".join(f"| `{claim}` | {doc} |" for claim, doc in state.doc_drift_top)
        more = (
            f"\n| … | _+{state.doc_drift_total - len(state.doc_drift_top)} more_ |"
            if state.doc_drift_total > len(state.doc_drift_top)
            else ""
        )
        out += (
            f"**{state.doc_drift_total} potential drift** — the docs name code the graph "
            "doesn't have (renamed or removed symbols, or prose the binder can't resolve).\n\n"
            f"| The docs claim… | …in |\n|---|---|\n{rows}{more}\n\n"
        )
    return out


def _api_split_block(store: FactStore, src: str | None) -> str:
    """The public surface against the machinery behind it.

    A 2,000-symbol repo sounds unreadable until you learn 40 of those symbols are the
    API and the rest is implementation — the same codebase, reframed as approachable.
    """
    from orchestrator.knowledge.insights import api_split

    split = api_split(store)
    # Nothing classifiable (a pure Java/C# repo) — say nothing rather than imply the
    # whole codebase is public. The section is an aid, not an obligation.
    if not split.total:
        return ""
    imp = Importance(store)
    listed = ", ".join(_link(n, src) for n in imp.rank(split.public)[:_MAX_PUBLIC_SYMBOLS])
    rest = len(split.public) - _MAX_PUBLIC_SYMBOLS
    unknown = (
        f" {split.unknown_count} symbol{'s' if split.unknown_count != 1 else ''} in languages "
        "whose visibility the graph can't read are left out of this count."
        if split.unknown_count
        else ""
    )
    return (
        "## Public surface\n"
        f"_Split by each language's own rule — {split.rules}._\n\n"
        f"**{len(split.public)} public** symbols · **{split.internal_count} internal**, "
        f"of {split.total}. Most of this codebase is machinery you don't need to read to "
        f"use it.{unknown}\n\n"
        f"Most-depended-upon public symbols: {listed}" + (f", +{rest} more" if rest > 0 else "") + "\n\n"
    )


def _cycles_block(deps: ModuleDeps, store: FactStore) -> str:
    """Modules that import each other, directly or through a chain.

    Invisible before intra-package imports resolved — the graph had almost no
    first-party import edges to form a cycle with.
    """
    from orchestrator.knowledge.insights import import_cycles

    cycles = import_cycles(deps.imports)
    if not cycles:
        return ""
    shown = cycles[:_MAX_CYCLES]
    rows: list[str] = []
    for cycle in shown:
        names = [n.name for i in cycle if (n := store.node(i)) is not None]
        listed = " ↔ ".join(f"`{n}`" for n in names[:_MAX_CYCLE_MEMBERS])
        rest = len(names) - _MAX_CYCLE_MEMBERS
        rows.append(f"- {len(cycle)} modules: {listed}" + (f", +{rest} more" if rest > 0 else ""))
    tail = f"\n\n_Showing {len(shown)} of {len(cycles)} cycles._" if len(cycles) > len(shown) else ""
    # How bad a cycle is depends on the language. A Python circular import can fail at
    # runtime; mutual `#include` in C compiles fine because of include guards, so calling
    # it "a hazard for import order" there overstates a design smell into a bug.
    langs = {n.language for cycle in shown for i in cycle if (n := store.node(i)) is not None}
    if langs and langs <= _C_FAMILY:
        severity = (
            "In C/C++ include guards make these compile cleanly, so read them as a design "
            "smell — layering that doesn't hold — rather than a defect."
        )
    elif langs & _C_FAMILY:
        severity = (
            "Severity varies by language: a circular import can fail at runtime, while "
            "mutual `#include` in C/C++ compiles fine behind include guards."
        )
    else:
        severity = "Each is a place the layering doesn't hold — and a hazard for import order."
    return (
        "## Import cycles\n"
        f"_Groups of modules that depend on each other, directly or through a chain. "
        f"{severity}_\n\n" + "\n".join(rows) + tail + "\n\n"
    )


def _dead_code_block(store: FactStore, src: str | None) -> str:
    """Internal symbols nothing appears to call — candidates only, and said so."""
    from orchestrator.knowledge.insights import dead_code_candidates

    dead = dead_code_candidates(store)
    if not dead.candidates:
        return ""
    listed = ", ".join(_link(n, src) for n in dead.candidates)
    tail = f", +{dead.total - len(dead.candidates)} more" if dead.total > len(dead.candidates) else ""
    return (
        "## Possibly unused\n"
        f"_**{dead.total} of {dead.considered} internal symbols** have no caller, subclass "
        "or doc reference in the graph. **Candidates, not verdicts**: calls through an "
        "attribute chain are skipped rather than guessed at, and dynamic dispatch, "
        "registries and reflection are invisible. Public symbols are excluded — having no "
        "in-repo caller is what being an API looks like._\n\n"
        f"{listed}{tail}\n\n"
    )


def _complexity_block(state: CurrentState) -> str:
    """Where the bulk sits — the size distribution and the biggest types.

    Takes the slot the raw node-kind counts used to occupy. "173 types, 12 of them over
    25 members, here are the largest" is orientation; "Type: 173" is a statistic.
    """
    if not state.size_dist and not state.hotspots:
        return ""
    out = "## Complexity\n_How big the types are, and which are biggest._\n\n"
    if state.size_dist:
        out += (
            "Size distribution: "
            + " · ".join(f"**{v}** {k}" for k, v in state.size_dist.most_common())
            + "\n\n"
        )
    if state.hotspots:
        rows = "\n".join(f"| `{n}` | {c} | `{loc}` |" for n, c, loc in state.hotspots[:10])
        out += f"| Largest type | Members | Defined at |\n|---|---|---|\n{rows}\n\n"
    return out


def _test_coverage_block(state: CurrentState) -> str:
    """Which components the tests reach at all — the question before "how well".

    Measured by test→source imports, so it says a component is *exercised*, not that
    its behaviour is well covered. Bounded honestly: a test reaching a component
    through a runtime lookup the graph can't see reads here as no test at all.
    """
    if not state.production_areas:
        return ""
    untested = ""
    if state.untested_top:
        listed = ", ".join(f"`{a}` ({c} type{'s' if c != 1 else ''})" for a, c in state.untested_top)
        untested = f"\n\nLargest components no test imports: {listed}."
    return (
        "## Test coverage\n"
        "_Which components the test suite reaches, by test→source imports. Presence, "
        "not line coverage._\n\n"
        f"**{state.tested_areas} of {state.production_areas} components** are imported "
        f"by at least one test.{untested}\n\n"
    )


def render_architecture(
    store: FactStore,
    stats: GraphStats,
    *,
    greenfield: bool,
    src: str | None = None,
    page_of: dict[str, str] | None = None,
    areas: list[AreaFacts] | None = None,
    area_pages: dict[str, str] | None = None,
    state: CurrentState | None = None,
    deps: ModuleDeps | None = None,
) -> str:
    """Architecture overview — the top of the walk.

    ``src`` is the relative path from this document to the repo root, enabling source
    deep-links; ``None`` renders locations as plain text. ``page_of`` maps module id →
    page stem: a module with a page links *down* to it (the page carries the detail),
    one without links straight to its source. ``areas`` + ``area_pages`` add the coarser
    component level above modules. ``state`` carries the shared analysis (see
    ``knowledge/analysis.py``) that adds the system-architecture diagram, layers, and
    test coverage — the sections `state` used to print and the committed bank lacked.
    """
    pages = page_of or {}
    apages = area_pages or {}
    if greenfield or stats.total_nodes == 0:
        return _doc("Architecture", _GREENFIELD_NOTE)

    # Node counts read as a database-stats dump when given a section of their own
    # ("Function: 1938, Field: 400") — low signal for someone trying to orient. Folded
    # into one line under the graph size, where they belong as scale, not as content.
    counts = " · ".join(
        f"{n} {kind.value.lower()}s"
        for kind, n in sorted(stats.node_counts.items(), key=lambda kv: (-kv[1], kv[0].value))
        if n
    )

    # Module map: first-party SOURCE modules (tests excluded) and their members (top 25).
    modules = {
        n.id: n
        for n in store.nodes
        if n.kind is NodeKind.MODULE and not n.external and not _is_test_module(n.name)
    }
    members: dict[str, dict[str, int]] = defaultdict(lambda: {"Type": 0, "Function": 0})
    for mod_id in modules:
        for child in store.children_of(mod_id):
            if child.kind is NodeKind.TYPE:
                members[mod_id]["Type"] += 1
            elif child.kind is NodeKind.FUNCTION:
                members[mod_id]["Function"] += 1
    # Tie-break on name: size alone leaves equal-sized modules in dict order, which
    # reshuffles this list whenever unrelated code moves. Committed docs must diff clean.
    ranked = sorted(
        ((mid, c) for mid, c in members.items() if c["Type"] or c["Function"]),
        key=lambda kv: (-(kv[1]["Type"] + kv[1]["Function"]), modules[kv[0]].name),
    )[:25]

    def _map_link(mid: str) -> str:
        mod = modules[mid]
        if mid in pages:
            return f"[`{mod.name}`]({MODULES_SUBDIR}/{pages[mid]}.md)"
        return _link(mod, src)

    module_lines = (
        "\n".join(f"- {_map_link(mid)} — {c['Type']} types, {c['Function']} functions" for mid, c in ranked)
        or "- (no first-party modules with members)"
    )
    shown, total = len(ranked), sum(1 for c in members.values() if c["Type"] or c["Function"])
    if total > shown:
        module_lines += f"\n\n_Showing the {shown} biggest of {total} first-party modules._"

    # Rank by call count, but only over code this project owns. Raw `top_called_functions`
    # is dominated by stdlib/third-party symbols called from tests — on this repo the top
    # entries were `pytest.raises`, `json.dumps`, `httpx.AsyncClient`, `os.getenv`. A blast
    # radius for `json.dumps` is worse than noise: you cannot change it, so it crowds out
    # the code you can. Externals have no provenance (`grounded` is False); test helpers
    # are excluded the same way the module map excludes them.
    first_party = [
        f
        for f in stats.top_called_functions
        if (n := store.node(f.node_id)) is not None and n.grounded and not _under_tests(n)
    ]
    # Re-rank on PRODUCTION call-sites. The raw count sums both, so a helper called by
    # thirty tests and two callers outranks one the system genuinely leans on — click's
    # "most depended-upon" callers for `echo` were test_echo, test_echo_color_flag,
    # test_echo_custom_file. Both numbers are shown, because "10 production · 22 test"
    # says more than either alone: the second is a coverage signal, not a design one.
    imp = Importance(store)
    first_party.sort(key=lambda f: (-imp.prod_callers[f.node_id], -f.call_count, f.name))
    hot: list[str] = []
    for f in first_party[:_BLAST_RADIUS_HOTSPOTS]:
        node = store.node(f.node_id)
        label = _link(node, src) if node is not None else f"`{f.name}`"
        # Blast radius: not just who calls it, but everything a change here can reach,
        # transitively. `call_count` is direct callers only and understates the risk.
        reach = store.impact_of(f.node_id)
        radius = ""
        if reach:
            hops = max(d for _, d in reach)
            radius = f" · **reaches {len(reach)} symbols** (≤{hops} hop{'s' if hops != 1 else ''})"
        split = imp.caller_split(f.node_id) or f"{f.call_count} call-sites"
        hot.append(f"- {label} — {split}{radius}{_caller_line(store, f.node_id, src)}")
    hotspots = "\n".join(hot) or "- (no call edges extracted for this language)"

    area_block = ""
    if areas:
        rows = "\n".join(
            f"| {f'[`{a.name}`]({AREAS_SUBDIR}/{apages[a.name]}.md)' if a.name in apages else f'`{a.name}`'} "
            f"| {a.zone} | {len(a.modules)} | {a.types} | {a.functions} |"
            for a in areas
        )
        area_block = (
            "## Areas\nThe coarse components — start here, then drill into a module. "
            "An area is a module's first two path or namespace segments.\n\n"
            "| Area | Zone | Modules | Types | Functions |\n|---|---|---|---|---|\n"
            f"{rows}\n\n"
        )

    analysis_blocks = _api_split_block(store, src)
    if deps is not None:
        analysis_blocks += _cycles_block(deps, store)
    if state is not None:
        analysis_blocks += (
            _system_architecture_block(state)
            + _layers_block(state)
            + _complexity_block(state)
            + _test_coverage_block(state)
            + _documentation_block(state)
        )
    analysis_blocks += _dead_code_block(store, src)

    body = (
        f"**Graph size:** {stats.total_nodes} nodes · {stats.total_edges} edges — {counts}.\n\n"
        f"{area_block}"
        f"{analysis_blocks}"
        f"## Module map (top 25 by members)\nThe biggest first-party modules — where the code lives. "
        f"Tests are excluded; each opens its page (or its source, if it has no page).\n\n{module_lines}\n\n"
        f"## Call hotspots (most-called functions)\nThe most-depended-on functions: what breaks the most "
        f"if you change it. Each links to its definition and to its direct callers; **reaches** is the "
        f"transitive blast radius — every symbol a change here can touch.\n\n{hotspots}"
    )
    return _doc("Architecture", body)


def render_domain_model(
    store: FactStore, *, src: str | None = None, entity_pages: dict[str, str] | None = None
) -> str:
    """The data model: every table, its foreign keys **both ways**, linked to its page.

    Foreign keys are rendered from both ends. Listing only ``references_of`` answers "what
    does this table point at" and leaves the more important question — "who depends on this
    table, so what breaks if I change it" — unanswerable from the page.
    """
    pages = entity_pages or {}
    entities = [n for n in store.nodes if n.kind is NodeKind.ENTITY]
    if not entities:
        return _core_types_page(store, src)

    def _cell(nodes: list[Node]) -> str:
        if not nodes:
            return "—"
        return ", ".join(
            f"[`{n.name}`]({ENTITIES_SUBDIR}/{pages[n.id]}.md)" if n.id in pages else f"`{n.name}`"
            for n in sorted(nodes, key=lambda n: (n.name, n.id))
        )

    rows: list[str] = []
    for ent in sorted(entities, key=lambda n: (n.name, n.id)):
        fields = [c for c in store.children_of(ent.id) if c.kind is NodeKind.FIELD]
        name = f"[`{ent.name}`]({ENTITIES_SUBDIR}/{pages[ent.id]}.md)" if ent.id in pages else _link(ent, src)
        rows.append(
            f"| {name} | {len(fields)} | {_cell(store.references_of(ent.id))} "
            f"| {_cell(store.dependents_of(ent.id))} |"
        )

    body = (
        f"{len(entities)} table{'s' if len(entities) != 1 else ''}. **Referenced by** is the "
        "half that matters when you're about to change one — those are the tables that "
        "depend on it.\n\n"
        "| Table | Fields | References | Referenced by |\n|---|---|---|---|\n" + "\n".join(rows)
    )
    return _doc("Domain model", body)


def _naming_block(store: FactStore) -> str:
    """The house style the code actually follows, counted rather than asserted.

    ``conventions.md`` carried four sampled rules and a lint config — true, but it left
    the questions a newcomer asks unanswered: what do you call things here, where do
    tests live, how are errors signalled? All three are countable from the graph, and a
    counted convention ("94% of functions are snake_case") is worth more than a claimed
    one because the exceptions are visible in the number.
    """
    funcs = [n for n in store.nodes if n.kind is NodeKind.FUNCTION and n.grounded and not _under_tests(n)]
    types = [n for n in store.nodes if n.kind is NodeKind.TYPE and n.grounded and not _under_tests(n)]
    lines: list[str] = []

    def dominant(names: list[str], patterns: dict[str, re.Pattern[str]]) -> tuple[str, int] | None:
        if not names:
            return None
        hits = {label: sum(1 for n in names if pat.fullmatch(n)) for label, pat in patterns.items()}
        label, count = max(hits.items(), key=lambda kv: (kv[1], kv[0]))
        return (label, round(100 * count / len(names))) if count else None

    fn_style = dominant(
        [n.name for n in funcs if not n.name.startswith("__")],
        {
            "snake_case": re.compile(r"_?[a-z][a-z0-9]*(_[a-z0-9]+)*"),
            "camelCase": re.compile(r"[a-z][a-zA-Z0-9]*"),
            "PascalCase": re.compile(r"[A-Z][a-zA-Z0-9]*"),
        },
    )
    if fn_style:
        lines.append(f"- **Functions** are `{fn_style[0]}` ({fn_style[1]}% of {len(funcs)}).")
    type_style = dominant(
        [n.name for n in types],
        {
            "PascalCase": re.compile(r"_?[A-Z][a-zA-Z0-9]*"),
            "snake_case": re.compile(r"_?[a-z][a-z0-9]*(_[a-z0-9]+)*"),
        },
    )
    if type_style:
        lines.append(f"- **Types** are `{type_style[0]}` ({type_style[1]}% of {len(types)}).")
    private = sum(1 for n in funcs if n.name.startswith("_") and not n.name.startswith("__"))
    if private:
        lines.append(
            f"- **{private} of {len(funcs)} functions** are underscore-private — the public "
            "surface is the rest."
        )
    return "\n\n**Naming**\n" + "\n".join(lines) if lines else ""


def _test_layout_block(store: FactStore) -> str:
    """Where tests live and what they're called — the first thing you need to add one."""
    test_mods = [n for n in store.nodes if n.kind is NodeKind.MODULE and n.grounded and _under_tests(n)]
    if not test_mods:
        return "\n\n**Tests**\n\n- No test modules found in the graph."
    dirs = Counter((n.provenance.file.rsplit("/", 1)[0] if n.provenance else "") for n in test_mods)
    top = ", ".join(f"`{d}/` ({c})" for d, c in dirs.most_common(4) if d)
    prefixed = sum(1 for n in test_mods if n.name.rsplit(".", 1)[-1].startswith("test_"))
    style = (
        f"named `test_*.py` ({round(100 * prefixed / len(test_mods))}%)"
        if prefixed
        else "no dominant naming pattern"
    )
    return f"\n\n**Tests**\n\n- **{len(test_mods)} test modules**, {style}.\n- They live in {top}."


def _error_idiom_block(store: FactStore) -> str:
    """How this codebase signals failure — its own exception hierarchy, if it has one.

    Found by walking ``IMPLEMENTS`` down from anything that extends a built-in
    exception, not by matching names. Click's hierarchy is ``Abort``, ``Exit``,
    ``NoSuchOption``, ``BadParameter`` — a name-suffix rule finds four of them and
    would state that undercount as a fact.
    """
    by_id = {n.id: n for n in store.nodes}
    seeds = {
        n.id
        for n in store.nodes
        if n.kind is NodeKind.TYPE
        and n.grounded
        and not _under_tests(n)
        and any(base.name.endswith(("Error", "Exception")) for base in store.implements_of(n.id))
    }
    # Transitively close: a subclass of a project exception is a project exception.
    errors, frontier = set(seeds), list(seeds)
    while frontier:
        for sub in store.implementors_of(frontier.pop()):
            if sub.id not in errors and sub.grounded and not _under_tests(sub):
                errors.add(sub.id)
                frontier.append(sub.id)
    if not errors:
        return ""

    imp = Importance(store)
    nodes = [by_id[i] for i in errors if i in by_id]
    # The ones worth naming are the ones others extend — the roots of the hierarchy.
    roots = [n for n in nodes if imp.implementors[n.id]] or nodes
    listed = ", ".join(f"`{n.name}`" for n in imp.rank(roots)[:6])
    return (
        f"\n\n**Errors**\n\n- **{len(errors)} exception types** of its own, "
        f"rooted at {listed}. Failure is signalled by raising these, not by return codes."
    )


def render_conventions(root: Path, store: FactStore | None = None) -> str:
    from orchestrator.sdlc.conventions import extract_conventions

    conv = extract_conventions(root)
    lint = [
        name
        for name in ("ruff.toml", ".ruff.toml", ".eslintrc", ".eslintrc.json", ".prettierrc")
        if (root / name).is_file()
    ]
    if (root / "pyproject.toml").is_file():
        try:
            if "[tool.ruff" in (root / "pyproject.toml").read_text(encoding="utf-8"):
                lint.append("pyproject [tool.ruff]")
        except OSError:
            pass
    parts: list[str] = []
    block = conv.prompt_block()
    if block:
        # The digest is phrased as codegen instructions; keep the observed rules.
        parts.append(block.split("\n", 1)[1] if "\n" in block else block)
    else:
        parts.append("_No conventions sampled yet._")
    if lint:
        parts.append("\n**Lint/format configs:** " + ", ".join(f"`{c}`" for c in lint))
    if conv.top_package:
        parts.append(f"\n**Top-level package:** `{conv.top_package}`")
    if store is not None:
        parts.append(_naming_block(store) + _test_layout_block(store) + _error_idiom_block(store))
    return _doc("Conventions", "\n".join(parts))


def render_glossary(store: FactStore, *, src: str | None = None) -> str:
    """The vocabulary of the codebase — each term pointing at where it's defined or explained.

    This used to be sixty alphabetical lines of ``**Abort** — _TODO: definition_``: a
    to-do list addressed to nobody, which is the least useful thing a generated page can
    be. The graph can't write definitions, but it knows two things that are worth more
    than a placeholder — where the term is defined, and which doc explains it — so the
    page says those and stops claiming a definition is coming.
    """
    # Underscore-private types are implementation detail, not vocabulary — and they'd
    # otherwise sort to the top of an alphabetical list and be the first thing read.
    terms = [
        n
        for n in store.nodes
        if n.kind in (NodeKind.ENTITY, NodeKind.TYPE)
        and not n.external
        and not _under_tests(n)
        and not n.name.startswith("_")
    ]
    if not terms:
        return _doc("Glossary", "_No domain terms extracted yet._")

    imp = Importance(store)
    # Rank first (the terms worth knowing), then alphabetise the survivors — a glossary
    # is something you look a word up in.
    ranked = sorted(imp.rank(terms)[:_MAX_GLOSSARY_TERMS], key=lambda n: (n.name.lower(), n.id))
    rows: list[str] = []
    for t in ranked:
        docs = sorted({d.id: d for d in store.docs_for(t.id)}.values(), key=lambda n: (n.name, n.id))
        explained = ", ".join(f"`{d.name}`" for d in docs[:2]) if docs else "—"
        rows.append(f"| **{t.name}** | {_link(t, src)} | {explained} |")

    body = (
        "_The codebase's vocabulary, most-depended-upon first, then alphabetical. "
        "Definitions aren't generated — a term links to where it's defined, and to the "
        "doc that explains it where the docs name one._\n\n"
        "| Term | Defined at | Explained in |\n|---|---|---|\n" + "\n".join(rows)
    )
    if len(terms) > len(ranked):
        body += f"\n\n_Top {len(ranked)} of {len(terms)} types by graph centrality._"
    return _doc("Glossary", body)


def render_symbol_index(store: FactStore, *, page_of: dict[str, str], src: str | None = None) -> str:
    """One A–Z page: every symbol → the page that describes it.

    Makes the knowledge base searchable without grep, which matters most for the reader
    who has a name and no idea where it lives — the case every other page assumes away
    by starting from structure.
    """
    parents = store.parents_index()
    rows: list[tuple[str, str, str]] = []  # (sort key, name, cell)
    for n in store.nodes:
        if n.kind not in (NodeKind.TYPE, NodeKind.FUNCTION) or not n.grounded or _under_tests(n):
            continue
        # Dunders are language protocol, not vocabulary — and being alphabetically first
        # they'd fill the top of the index with `__call__` repeated once per class.
        if n.name.startswith("__") and n.name.endswith("__"):
            continue
        module_id = parents.get(n.id)
        # A method's parent is its type; climb to the owning module.
        while module_id is not None and (owner := store.node(module_id)) is not None:
            if owner.kind is NodeKind.MODULE:
                break
            module_id = parents.get(module_id)
        owner = store.node(module_id) if module_id else None
        if owner is not None and owner.id in page_of:
            where = f"[`{owner.name}`]({MODULES_SUBDIR}/{page_of[owner.id]}.md#{_anchor(n.name)})"
        elif owner is not None:
            where = f"`{owner.name}`"
        else:
            where = "—"
        rows.append((n.name.lower(), n.name, f"| `{n.name}` | {where} | {_link(n, src)} |"))

    if not rows:
        return _doc("Symbol index", "_No symbols extracted yet._")
    rows.sort(key=lambda r: (r[0], r[2]))
    shown = rows[:_MAX_INDEX_SYMBOLS]
    body = (
        f"_Every first-party symbol, A–Z, and the page that describes it. "
        f"{len(rows)} symbols; tests excluded._\n\n"
        "| Symbol | On page | Defined at |\n|---|---|---|\n" + "\n".join(r[2] for r in shown)
    )
    if len(rows) > len(shown):
        body += f"\n\n_Showing the first {len(shown)} of {len(rows)}._"
    return _doc("Symbol index", body)


def _anchor(name: str) -> str:
    """GitHub's heading anchor for a ``### `name``` symbol section."""
    return re.sub(r"[^a-z0-9_-]+", "", name.lower())


def render_onboarding(steps: list[OnboardingStep], src: str | None = None) -> str:
    """ "New here? Read these, in this order." — rendered inline on the index page."""
    if not steps:
        return ""
    lines = [f"{i}. {_link(s.module, src)} — {s.why}" for i, s in enumerate(steps, start=1)]
    return (
        "## New here? Read these first\n"
        "_Where execution starts, then what the most code depends on._\n\n" + "\n".join(lines) + "\n\n"
    )


def has_api_surface(store: FactStore) -> bool:
    """Does this repo expose routes the graph can see? Gates the API-surface page."""
    return any(n.kind is NodeKind.ENDPOINT for n in store.nodes)


def render_api_surface(store: FactStore, *, src: str | None = None) -> str:
    """Every route this service exposes, and the code behind it.

    The first thing anyone wants from a web service, and the graph has carried
    ``Endpoint`` nodes and ``EXPOSES`` edges the whole time with nothing rendering them.
    Only written when a repo actually has routes — an empty "API surface" page on a
    library would imply the library has none to find, which is a different claim from
    "this language's front-end doesn't extract them yet".
    """
    endpoints = sorted((n for n in store.nodes if n.kind is NodeKind.ENDPOINT), key=lambda n: (n.name, n.id))
    handlers: dict[str, list[Node]] = defaultdict(list)
    for e in store.edges_of_kind(EdgeKind.EXPOSES):
        target = store.node(e.dst)
        if target is not None:
            handlers[e.src].append(target)

    rows: list[str] = []
    for ep in endpoints:
        served = sorted({n.id: n for n in handlers.get(ep.id, [])}.values(), key=lambda n: (n.name, n.id))
        handled = ", ".join(_link(n, src) for n in served) or "—"
        where = _link(ep, src, label=str(ep.provenance)) if ep.provenance else "—"
        rows.append(f"| `{ep.name}` | {handled} | {where} |")

    body = (
        f"**{len(endpoints)} endpoint{'s' if len(endpoints) != 1 else ''}** exposed by this "
        "service, each with the code that serves it.\n\n"
        "| Route | Handler | Declared at |\n|---|---|---|\n" + "\n".join(rows)
    )
    return _doc("API surface", body)


def render_progress_pointer(state: CurrentState | None = None) -> str:
    """Where the project stands: what the graph suggests doing, then where work is tracked.

    The recommendations are the same prioritized list `state` prints, computed from the
    metrics (untested areas, fat controllers, god classes, duplicate names). They lead,
    because on a brownfield repo the `BACKLOG.md` pointer alone describes a file that
    doesn't exist unless Spine built the project.
    """
    body = ""
    if state is not None and state.recommendations:
        listed = "\n".join(f"- **{pri}** — {text}" for pri, text in state.recommendations)
        body += (
            "## Suggested next steps\n"
            "_Derived from the graph — untested components, oversized types, duplicate "
            "names. Advisory, and only as good as what the graph can see._\n\n"
            f"{listed}\n\n"
        )
    body += (
        "## Feature tracking\n"
        "Feature progress is tracked in **`BACKLOG.md`** (written by `sdlc feature` / "
        "`orchestrator backlog`): `[ ]` todo, `[~]` in progress, `[x]` done (PR merged)."
    )
    return _doc("Progress", body)


def render_index(
    root: Path,
    *,
    greenfield: bool,
    summary: dict[str, int],
    module_pages: int = 0,
    area_pages: int = 0,
    entity_pages: int = 0,
    stamp: str = "",
    api_surface: bool = False,
    onboarding: str = "",
) -> str:
    kind = "greenfield" if greenfield else "brownfield"
    pages_line = (
        f"- [`{AREAS_SUBDIR}/`]({AREAS_SUBDIR}/) — {area_pages} area pages: what each component is, "
        "what it depends on, and a map of its neighbours\n"
        if area_pages
        else ""
    )
    pages_line += (
        f"- [`{MODULES_SUBDIR}/`]({MODULES_SUBDIR}/) — {module_pages} module pages: every symbol, "
        "who calls it, and what it calls\n"
        if module_pages
        else ""
    )
    pages_line += (
        f"- [`{ENTITIES_SUBDIR}/`]({ENTITIES_SUBDIR}/) — {entity_pages} table pages: columns, "
        "foreign keys both ways, and the code that reads or writes it\n"
        if entity_pages
        else ""
    )
    body = (
        f"Code-true knowledge base for **{project_name(root)}** ({kind}), built by "
        "`orchestrator understand` from the Product Knowledge Graph + project profile.\n\n"
    )
    if stamp:
        body += f"{stamp}\n\n"
    body += (
        f"**Graph:** {summary.get('grounded_nodes', 0)} grounded nodes · {summary.get('edges', 0)} edges.\n\n"
        "> **epistēmē** (ἐπιστήμη) — knowledge grounded in evidence, as opposed to *doxa*, "
        "opinion. Everything here is derived from the code itself, not written by hand.\n\n"
        f"{onboarding}"
        "## Files\n"
        "- [architecture.md](architecture.md) — module map, node kinds, call hotspots\n"
        f"{pages_line}"
        "- [domain-model.md](domain-model.md) — tables, fields, foreign keys both ways\n"
        + ("- [api-surface.md](api-surface.md) — every route and the code behind it\n" if api_surface else "")
        + "- [tech-context.md](tech-context.md) — languages, framework, db, tests\n"
        "- [conventions.md](conventions.md) — observed house style + lint config\n"
        "- [glossary.md](glossary.md) — domain terms\n"
        "- [symbol-index.md](symbol-index.md) — every symbol, A–Z, and the page it's on\n"
        "- [progress.md](progress.md) → `BACKLOG.md`\n\n"
        "**Start at [architecture.md](architecture.md)** and click down: area → module → "
        "symbol → its source. Every relationship is rendered from both ends, so you can "
        "always walk back.\n\n"
        "_Regenerate with `orchestrator understand .` — structural files are rendered from "
        "code, so edits are advisory._"
    )
    return _doc("Episteme", body)


__all__ = [
    "MAX_MODULE_PAGES",
    "MODULES_SUBDIR",
    "STAMP_CLOSE",
    "STAMP_OPEN",
    "module_page_slugs",
    "render_architecture",
    "render_stamp",
    "strip_stamp",
    "render_module_page",
    "select_module_pages",
    "render_conventions",
    "render_domain_model",
    "render_glossary",
    "render_index",
    "render_progress_pointer",
    "render_tech_context",
]
